// Code generated by ent, DO NOT EDIT.

package propertyimage

import (
	"immo-lux/internal/database/ent/client/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldLTE(FieldID, id))
}

// PropertyID applies equality check predicate on the "property_id" field. It's identical to PropertyIDEQ.
func PropertyID(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldPropertyID, v))
}

// ImageData applies equality check predicate on the "image_data" field. It's identical to ImageDataEQ.
func ImageData(v []byte) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldImageData, v))
}

// ContentType applies equality check predicate on the "content_type" field. It's identical to ContentTypeEQ.
func ContentType(v string) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldContentType, v))
}

// FileSize applies equality check predicate on the "file_size" field. It's identical to FileSizeEQ.
func FileSize(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldFileSize, v))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldHeight, v))
}

// DisplayOrder applies equality check predicate on the "display_order" field. It's identical to DisplayOrderEQ.
func DisplayOrder(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldDisplayOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldCreatedAt, v))
}

// PropertyIDEQ applies the EQ predicate on the "property_id" field.
func PropertyIDEQ(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldPropertyID, v))
}

// PropertyIDNEQ applies the NEQ predicate on the "property_id" field.
func PropertyIDNEQ(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNEQ(FieldPropertyID, v))
}

// PropertyIDIn applies the In predicate on the "property_id" field.
func PropertyIDIn(vs ...int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldIn(FieldPropertyID, vs...))
}

// PropertyIDNotIn applies the NotIn predicate on the "property_id" field.
func PropertyIDNotIn(vs ...int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNotIn(FieldPropertyID, vs...))
}

// ImageDataEQ applies the EQ predicate on the "image_data" field.
func ImageDataEQ(v []byte) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldImageData, v))
}

// ImageDataNEQ applies the NEQ predicate on the "image_data" field.
func ImageDataNEQ(v []byte) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNEQ(FieldImageData, v))
}

// ImageDataIn applies the In predicate on the "image_data" field.
func ImageDataIn(vs ...[]byte) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldIn(FieldImageData, vs...))
}

// ImageDataNotIn applies the NotIn predicate on the "image_data" field.
func ImageDataNotIn(vs ...[]byte) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNotIn(FieldImageData, vs...))
}

// ImageDataGT applies the GT predicate on the "image_data" field.
func ImageDataGT(v []byte) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldGT(FieldImageData, v))
}

// ImageDataGTE applies the GTE predicate on the "image_data" field.
func ImageDataGTE(v []byte) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldGTE(FieldImageData, v))
}

// ImageDataLT applies the LT predicate on the "image_data" field.
func ImageDataLT(v []byte) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldLT(FieldImageData, v))
}

// ImageDataLTE applies the LTE predicate on the "image_data" field.
func ImageDataLTE(v []byte) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldLTE(FieldImageData, v))
}

// ContentTypeEQ applies the EQ predicate on the "content_type" field.
func ContentTypeEQ(v string) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldContentType, v))
}

// ContentTypeNEQ applies the NEQ predicate on the "content_type" field.
func ContentTypeNEQ(v string) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNEQ(FieldContentType, v))
}

// ContentTypeIn applies the In predicate on the "content_type" field.
func ContentTypeIn(vs ...string) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldIn(FieldContentType, vs...))
}

// ContentTypeNotIn applies the NotIn predicate on the "content_type" field.
func ContentTypeNotIn(vs ...string) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNotIn(FieldContentType, vs...))
}

// ContentTypeGT applies the GT predicate on the "content_type" field.
func ContentTypeGT(v string) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldGT(FieldContentType, v))
}

// ContentTypeGTE applies the GTE predicate on the "content_type" field.
func ContentTypeGTE(v string) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldGTE(FieldContentType, v))
}

// ContentTypeLT applies the LT predicate on the "content_type" field.
func ContentTypeLT(v string) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldLT(FieldContentType, v))
}

// ContentTypeLTE applies the LTE predicate on the "content_type" field.
func ContentTypeLTE(v string) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldLTE(FieldContentType, v))
}

// ContentTypeContains applies the Contains predicate on the "content_type" field.
func ContentTypeContains(v string) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldContains(FieldContentType, v))
}

// ContentTypeHasPrefix applies the HasPrefix predicate on the "content_type" field.
func ContentTypeHasPrefix(v string) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldHasPrefix(FieldContentType, v))
}

// ContentTypeHasSuffix applies the HasSuffix predicate on the "content_type" field.
func ContentTypeHasSuffix(v string) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldHasSuffix(FieldContentType, v))
}

// ContentTypeEqualFold applies the EqualFold predicate on the "content_type" field.
func ContentTypeEqualFold(v string) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEqualFold(FieldContentType, v))
}

// ContentTypeContainsFold applies the ContainsFold predicate on the "content_type" field.
func ContentTypeContainsFold(v string) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldContainsFold(FieldContentType, v))
}

// FileSizeEQ applies the EQ predicate on the "file_size" field.
func FileSizeEQ(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldFileSize, v))
}

// FileSizeNEQ applies the NEQ predicate on the "file_size" field.
func FileSizeNEQ(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNEQ(FieldFileSize, v))
}

// FileSizeIn applies the In predicate on the "file_size" field.
func FileSizeIn(vs ...int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldIn(FieldFileSize, vs...))
}

// FileSizeNotIn applies the NotIn predicate on the "file_size" field.
func FileSizeNotIn(vs ...int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNotIn(FieldFileSize, vs...))
}

// FileSizeGT applies the GT predicate on the "file_size" field.
func FileSizeGT(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldGT(FieldFileSize, v))
}

// FileSizeGTE applies the GTE predicate on the "file_size" field.
func FileSizeGTE(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldGTE(FieldFileSize, v))
}

// FileSizeLT applies the LT predicate on the "file_size" field.
func FileSizeLT(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldLT(FieldFileSize, v))
}

// FileSizeLTE applies the LTE predicate on the "file_size" field.
func FileSizeLTE(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldLTE(FieldFileSize, v))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldLTE(FieldWidth, v))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldLTE(FieldHeight, v))
}

// DisplayOrderEQ applies the EQ predicate on the "display_order" field.
func DisplayOrderEQ(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldDisplayOrder, v))
}

// DisplayOrderNEQ applies the NEQ predicate on the "display_order" field.
func DisplayOrderNEQ(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNEQ(FieldDisplayOrder, v))
}

// DisplayOrderIn applies the In predicate on the "display_order" field.
func DisplayOrderIn(vs ...int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldIn(FieldDisplayOrder, vs...))
}

// DisplayOrderNotIn applies the NotIn predicate on the "display_order" field.
func DisplayOrderNotIn(vs ...int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNotIn(FieldDisplayOrder, vs...))
}

// DisplayOrderGT applies the GT predicate on the "display_order" field.
func DisplayOrderGT(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldGT(FieldDisplayOrder, v))
}

// DisplayOrderGTE applies the GTE predicate on the "display_order" field.
func DisplayOrderGTE(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldGTE(FieldDisplayOrder, v))
}

// DisplayOrderLT applies the LT predicate on the "display_order" field.
func DisplayOrderLT(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldLT(FieldDisplayOrder, v))
}

// DisplayOrderLTE applies the LTE predicate on the "display_order" field.
func DisplayOrderLTE(v int) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldLTE(FieldDisplayOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PropertyImage {
	return predicate.PropertyImage(sql.FieldLTE(FieldCreatedAt, v))
}

// HasProperty applies the HasEdge predicate on the "property" edge.
func HasProperty() predicate.PropertyImage {
	return predicate.PropertyImage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PropertyTable, PropertyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPropertyWith applies the HasEdge predicate on the "property" edge with a given conditions (other predicates).
func HasPropertyWith(preds ...predicate.Property) predicate.PropertyImage {
	return predicate.PropertyImage(func(s *sql.Selector) {
		step := newPropertyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PropertyImage) predicate.PropertyImage {
	return predicate.PropertyImage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PropertyImage) predicate.PropertyImage {
	return predicate.PropertyImage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PropertyImage) predicate.PropertyImage {
	return predicate.PropertyImage(sql.NotPredicates(p))
}
