// Code generated by ent, DO NOT EDIT.

package session

import (
	"immo-lux/internal/database/ent/client/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldUserID, v))
}

// SessionToken applies equality check predicate on the "session_token" field. It's identical to SessionTokenEQ.
func SessionToken(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldSessionToken, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldIsActive, v))
}

// RememberMe applies equality check predicate on the "remember_me" field. It's identical to RememberMeEQ.
func RememberMe(v bool) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldRememberMe, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldExpiresAt, v))
}

// InvalidatedAt applies equality check predicate on the "invalidated_at" field. It's identical to InvalidatedAtEQ.
func InvalidatedAt(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldInvalidatedAt, v))
}

// InvalidatedReason applies equality check predicate on the "invalidated_reason" field. It's identical to InvalidatedReasonEQ.
func InvalidatedReason(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldInvalidatedReason, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldIPAddress, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldUserAgent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldUserID, vs...))
}

// SessionTokenEQ applies the EQ predicate on the "session_token" field.
func SessionTokenEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldSessionToken, v))
}

// SessionTokenNEQ applies the NEQ predicate on the "session_token" field.
func SessionTokenNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldSessionToken, v))
}

// SessionTokenIn applies the In predicate on the "session_token" field.
func SessionTokenIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldSessionToken, vs...))
}

// SessionTokenNotIn applies the NotIn predicate on the "session_token" field.
func SessionTokenNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldSessionToken, vs...))
}

// SessionTokenGT applies the GT predicate on the "session_token" field.
func SessionTokenGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldSessionToken, v))
}

// SessionTokenGTE applies the GTE predicate on the "session_token" field.
func SessionTokenGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldSessionToken, v))
}

// SessionTokenLT applies the LT predicate on the "session_token" field.
func SessionTokenLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldSessionToken, v))
}

// SessionTokenLTE applies the LTE predicate on the "session_token" field.
func SessionTokenLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldSessionToken, v))
}

// SessionTokenContains applies the Contains predicate on the "session_token" field.
func SessionTokenContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldSessionToken, v))
}

// SessionTokenHasPrefix applies the HasPrefix predicate on the "session_token" field.
func SessionTokenHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldSessionToken, v))
}

// SessionTokenHasSuffix applies the HasSuffix predicate on the "session_token" field.
func SessionTokenHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldSessionToken, v))
}

// SessionTokenEqualFold applies the EqualFold predicate on the "session_token" field.
func SessionTokenEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldSessionToken, v))
}

// SessionTokenContainsFold applies the ContainsFold predicate on the "session_token" field.
func SessionTokenContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldSessionToken, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldIsActive, v))
}

// RememberMeEQ applies the EQ predicate on the "remember_me" field.
func RememberMeEQ(v bool) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldRememberMe, v))
}

// RememberMeNEQ applies the NEQ predicate on the "remember_me" field.
func RememberMeNEQ(v bool) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldRememberMe, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldExpiresAt, v))
}

// InvalidatedAtEQ applies the EQ predicate on the "invalidated_at" field.
func InvalidatedAtEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldInvalidatedAt, v))
}

// InvalidatedAtNEQ applies the NEQ predicate on the "invalidated_at" field.
func InvalidatedAtNEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldInvalidatedAt, v))
}

// InvalidatedAtIn applies the In predicate on the "invalidated_at" field.
func InvalidatedAtIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldInvalidatedAt, vs...))
}

// InvalidatedAtNotIn applies the NotIn predicate on the "invalidated_at" field.
func InvalidatedAtNotIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldInvalidatedAt, vs...))
}

// InvalidatedAtGT applies the GT predicate on the "invalidated_at" field.
func InvalidatedAtGT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldInvalidatedAt, v))
}

// InvalidatedAtGTE applies the GTE predicate on the "invalidated_at" field.
func InvalidatedAtGTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldInvalidatedAt, v))
}

// InvalidatedAtLT applies the LT predicate on the "invalidated_at" field.
func InvalidatedAtLT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldInvalidatedAt, v))
}

// InvalidatedAtLTE applies the LTE predicate on the "invalidated_at" field.
func InvalidatedAtLTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldInvalidatedAt, v))
}

// InvalidatedAtIsNil applies the IsNil predicate on the "invalidated_at" field.
func InvalidatedAtIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldInvalidatedAt))
}

// InvalidatedAtNotNil applies the NotNil predicate on the "invalidated_at" field.
func InvalidatedAtNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldInvalidatedAt))
}

// InvalidatedReasonEQ applies the EQ predicate on the "invalidated_reason" field.
func InvalidatedReasonEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldInvalidatedReason, v))
}

// InvalidatedReasonNEQ applies the NEQ predicate on the "invalidated_reason" field.
func InvalidatedReasonNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldInvalidatedReason, v))
}

// InvalidatedReasonIn applies the In predicate on the "invalidated_reason" field.
func InvalidatedReasonIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldInvalidatedReason, vs...))
}

// InvalidatedReasonNotIn applies the NotIn predicate on the "invalidated_reason" field.
func InvalidatedReasonNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldInvalidatedReason, vs...))
}

// InvalidatedReasonGT applies the GT predicate on the "invalidated_reason" field.
func InvalidatedReasonGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldInvalidatedReason, v))
}

// InvalidatedReasonGTE applies the GTE predicate on the "invalidated_reason" field.
func InvalidatedReasonGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldInvalidatedReason, v))
}

// InvalidatedReasonLT applies the LT predicate on the "invalidated_reason" field.
func InvalidatedReasonLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldInvalidatedReason, v))
}

// InvalidatedReasonLTE applies the LTE predicate on the "invalidated_reason" field.
func InvalidatedReasonLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldInvalidatedReason, v))
}

// InvalidatedReasonContains applies the Contains predicate on the "invalidated_reason" field.
func InvalidatedReasonContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldInvalidatedReason, v))
}

// InvalidatedReasonHasPrefix applies the HasPrefix predicate on the "invalidated_reason" field.
func InvalidatedReasonHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldInvalidatedReason, v))
}

// InvalidatedReasonHasSuffix applies the HasSuffix predicate on the "invalidated_reason" field.
func InvalidatedReasonHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldInvalidatedReason, v))
}

// InvalidatedReasonIsNil applies the IsNil predicate on the "invalidated_reason" field.
func InvalidatedReasonIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldInvalidatedReason))
}

// InvalidatedReasonNotNil applies the NotNil predicate on the "invalidated_reason" field.
func InvalidatedReasonNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldInvalidatedReason))
}

// InvalidatedReasonEqualFold applies the EqualFold predicate on the "invalidated_reason" field.
func InvalidatedReasonEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldInvalidatedReason, v))
}

// InvalidatedReasonContainsFold applies the ContainsFold predicate on the "invalidated_reason" field.
func InvalidatedReasonContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldInvalidatedReason, v))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressIsNil applies the IsNil predicate on the "ip_address" field.
func IPAddressIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldIPAddress))
}

// IPAddressNotNil applies the NotNil predicate on the "ip_address" field.
func IPAddressNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldIPAddress))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldIPAddress, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentIsNil applies the IsNil predicate on the "user_agent" field.
func UserAgentIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldUserAgent))
}

// UserAgentNotNil applies the NotNil predicate on the "user_agent" field.
func UserAgentNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldUserAgent))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldUserAgent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Session) predicate.Session {
	return predicate.Session(sql.NotPredicates(p))
}
