// Code generated by ent, DO NOT EDIT.

package property

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the property type in the database.
	Label = "property"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPropertyType holds the string denoting the property_type field in the database.
	FieldPropertyType = "property_type"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldIsPublished holds the string denoting the is_published field in the database.
	FieldIsPublished = "is_published"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldDistrict holds the string denoting the district field in the database.
	FieldDistrict = "district"
	// FieldMunicipality holds the string denoting the municipality field in the database.
	FieldMunicipality = "municipality"
	// FieldParish holds the string denoting the parish field in the database.
	FieldParish = "parish"
	// FieldPostalCode holds the string denoting the postal_code field in the database.
	FieldPostalCode = "postal_code"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldLatitude holds the string denoting the latitude field in the database.
	FieldLatitude = "latitude"
	// FieldLongitude holds the string denoting the longitude field in the database.
	FieldLongitude = "longitude"
	// FieldBedrooms holds the string denoting the bedrooms field in the database.
	FieldBedrooms = "bedrooms"
	// FieldBathrooms holds the string denoting the bathrooms field in the database.
	FieldBathrooms = "bathrooms"
	// FieldAreaSqm holds the string denoting the area_sqm field in the database.
	FieldAreaSqm = "area_sqm"
	// FieldLandAreaSqm holds the string denoting the land_area_sqm field in the database.
	FieldLandAreaSqm = "land_area_sqm"
	// FieldYearBuilt holds the string denoting the year_built field in the database.
	FieldYearBuilt = "year_built"
	// FieldFloor holds the string denoting the floor field in the database.
	FieldFloor = "floor"
	// FieldTotalFloors holds the string denoting the total_floors field in the database.
	FieldTotalFloors = "total_floors"
	// FieldParkingSpaces holds the string denoting the parking_spaces field in the database.
	FieldParkingSpaces = "parking_spaces"
	// FieldHasGarage holds the string denoting the has_garage field in the database.
	FieldHasGarage = "has_garage"
	// FieldHasGarden holds the string denoting the has_garden field in the database.
	FieldHasGarden = "has_garden"
	// FieldHasPool holds the string denoting the has_pool field in the database.
	FieldHasPool = "has_pool"
	// FieldHasElevator holds the string denoting the has_elevator field in the database.
	FieldHasElevator = "has_elevator"
	// FieldEnergyRating holds the string denoting the energy_rating field in the database.
	FieldEnergyRating = "energy_rating"
	// FieldVirtualTourURL holds the string denoting the virtual_tour_url field in the database.
	FieldVirtualTourURL = "virtual_tour_url"
	// FieldContactID holds the string denoting the contact_id field in the database.
	FieldContactID = "contact_id"
	// FieldPublisherID holds the string denoting the publisher_id field in the database.
	FieldPublisherID = "publisher_id"
	// FieldViewCount holds the string denoting the view_count field in the database.
	FieldViewCount = "view_count"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePublisher holds the string denoting the publisher edge name in mutations.
	EdgePublisher = "publisher"
	// EdgeContact holds the string denoting the contact edge name in mutations.
	EdgeContact = "contact"
	// EdgeImages holds the string denoting the images edge name in mutations.
	EdgeImages = "images"
	// Table holds the table name of the property in the database.
	Table = "properties"
	// PublisherTable is the table that holds the publisher relation/edge.
	PublisherTable = "properties"
	// PublisherInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	PublisherInverseTable = "users"
	// PublisherColumn is the table column denoting the publisher relation/edge.
	PublisherColumn = "publisher_id"
	// ContactTable is the table that holds the contact relation/edge.
	ContactTable = "properties"
	// ContactInverseTable is the table name for the Contact entity.
	// It exists in this package in order to avoid circular dependency with the "contact" package.
	ContactInverseTable = "contacts"
	// ContactColumn is the table column denoting the contact relation/edge.
	ContactColumn = "contact_id"
	// ImagesTable is the table that holds the images relation/edge.
	ImagesTable = "property_images"
	// ImagesInverseTable is the table name for the PropertyImage entity.
	// It exists in this package in order to avoid circular dependency with the "propertyimage" package.
	ImagesInverseTable = "property_images"
	// ImagesColumn is the table column denoting the images relation/edge.
	ImagesColumn = "property_id"
)

// Columns holds all SQL columns for property fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldDescription,
	FieldPropertyType,
	FieldPrice,
	FieldStatus,
	FieldIsPublished,
	FieldAddress,
	FieldDistrict,
	FieldMunicipality,
	FieldParish,
	FieldPostalCode,
	FieldCountry,
	FieldLatitude,
	FieldLongitude,
	FieldBedrooms,
	FieldBathrooms,
	FieldAreaSqm,
	FieldLandAreaSqm,
	FieldYearBuilt,
	FieldFloor,
	FieldTotalFloors,
	FieldParkingSpaces,
	FieldHasGarage,
	FieldHasGarden,
	FieldHasPool,
	FieldHasElevator,
	FieldEnergyRating,
	FieldVirtualTourURL,
	FieldContactID,
	FieldPublisherID,
	FieldViewCount,
	FieldPublishedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// PriceValidator is a validator for the "price" field. It is called by the builders before save.
	PriceValidator func(float64) error
	// DefaultIsPublished holds the default value on creation for the "is_published" field.
	DefaultIsPublished bool
	// AddressValidator is a validator for the "address" field. It is called by the builders before save.
	AddressValidator func(string) error
	// DistrictValidator is a validator for the "district" field. It is called by the builders before save.
	DistrictValidator func(string) error
	// MunicipalityValidator is a validator for the "municipality" field. It is called by the builders before save.
	MunicipalityValidator func(string) error
	// ParishValidator is a validator for the "parish" field. It is called by the builders before save.
	ParishValidator func(string) error
	// PostalCodeValidator is a validator for the "postal_code" field. It is called by the builders before save.
	PostalCodeValidator func(string) error
	// DefaultCountry holds the default value on creation for the "country" field.
	DefaultCountry string
	// CountryValidator is a validator for the "country" field. It is called by the builders before save.
	CountryValidator func(string) error
	// BedroomsValidator is a validator for the "bedrooms" field. It is called by the builders before save.
	BedroomsValidator func(int) error
	// BathroomsValidator is a validator for the "bathrooms" field. It is called by the builders before save.
	BathroomsValidator func(int) error
	// AreaSqmValidator is a validator for the "area_sqm" field. It is called by the builders before save.
	AreaSqmValidator func(float64) error
	// LandAreaSqmValidator is a validator for the "land_area_sqm" field. It is called by the builders before save.
	LandAreaSqmValidator func(float64) error
	// ParkingSpacesValidator is a validator for the "parking_spaces" field. It is called by the builders before save.
	ParkingSpacesValidator func(int) error
	// DefaultHasGarage holds the default value on creation for the "has_garage" field.
	DefaultHasGarage bool
	// DefaultHasGarden holds the default value on creation for the "has_garden" field.
	DefaultHasGarden bool
	// DefaultHasPool holds the default value on creation for the "has_pool" field.
	DefaultHasPool bool
	// DefaultHasElevator holds the default value on creation for the "has_elevator" field.
	DefaultHasElevator bool
	// VirtualTourURLValidator is a validator for the "virtual_tour_url" field. It is called by the builders before save.
	VirtualTourURLValidator func(string) error
	// ContactIDValidator is a validator for the "contact_id" field. It is called by the builders before save.
	ContactIDValidator func(int) error
	// PublisherIDValidator is a validator for the "publisher_id" field. It is called by the builders before save.
	PublisherIDValidator func(int) error
	// DefaultViewCount holds the default value on creation for the "view_count" field.
	DefaultViewCount int
	// ViewCountValidator is a validator for the "view_count" field. It is called by the builders before save.
	ViewCountValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// PropertyType defines the type for the "property_type" enum field.
type PropertyType string

// PropertyTypeHouse is the default value of the PropertyType enum.
const DefaultPropertyType = PropertyTypeHouse

// PropertyType values.
const (
	PropertyTypeHouse      PropertyType = "house"
	PropertyTypeApartment  PropertyType = "apartment"
	PropertyTypeVilla      PropertyType = "villa"
	PropertyTypeTownhouse  PropertyType = "townhouse"
	PropertyTypeLand       PropertyType = "land"
	PropertyTypeCommercial PropertyType = "commercial"
)

func (pt PropertyType) String() string {
	return string(pt)
}

// PropertyTypeValidator is a validator for the "property_type" field enum values. It is called by the builders before save.
func PropertyTypeValidator(pt PropertyType) error {
	switch pt {
	case PropertyTypeHouse, PropertyTypeApartment, PropertyTypeVilla, PropertyTypeTownhouse, PropertyTypeLand, PropertyTypeCommercial:
		return nil
	default:
		return fmt.Errorf("property: invalid enum value for property_type field: %q", pt)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusAvailable is the default value of the Status enum.
const DefaultStatus = StatusAvailable

// Status values.
const (
	StatusAvailable Status = "available"
	StatusPending   Status = "pending"
	StatusSold      Status = "sold"
	StatusRented    Status = "rented"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusAvailable, StatusPending, StatusSold, StatusRented:
		return nil
	default:
		return fmt.Errorf("property: invalid enum value for status field: %q", s)
	}
}

// EnergyRating defines the type for the "energy_rating" enum field.
type EnergyRating string

// EnergyRating values.
const (
	EnergyRatingAplus EnergyRating = "Aplus"
	EnergyRatingA     EnergyRating = "A"
	EnergyRatingB     EnergyRating = "B"
	EnergyRatingC     EnergyRating = "C"
	EnergyRatingD     EnergyRating = "D"
	EnergyRatingE     EnergyRating = "E"
	EnergyRatingF     EnergyRating = "F"
	EnergyRatingG     EnergyRating = "G"
)

func (er EnergyRating) String() string {
	return string(er)
}

// EnergyRatingValidator is a validator for the "energy_rating" field enum values. It is called by the builders before save.
func EnergyRatingValidator(er EnergyRating) error {
	switch er {
	case EnergyRatingAplus, EnergyRatingA, EnergyRatingB, EnergyRatingC, EnergyRatingD, EnergyRatingE, EnergyRatingF, EnergyRatingG:
		return nil
	default:
		return fmt.Errorf("property: invalid enum value for energy_rating field: %q", er)
	}
}

// OrderOption defines the ordering options for the Property queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPropertyType orders the results by the property_type field.
func ByPropertyType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPropertyType, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByIsPublished orders the results by the is_published field.
func ByIsPublished(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPublished, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByDistrict orders the results by the district field.
func ByDistrict(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDistrict, opts...).ToFunc()
}

// ByMunicipality orders the results by the municipality field.
func ByMunicipality(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMunicipality, opts...).ToFunc()
}

// ByParish orders the results by the parish field.
func ByParish(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParish, opts...).ToFunc()
}

// ByPostalCode orders the results by the postal_code field.
func ByPostalCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostalCode, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByLatitude orders the results by the latitude field.
func ByLatitude(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatitude, opts...).ToFunc()
}

// ByLongitude orders the results by the longitude field.
func ByLongitude(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLongitude, opts...).ToFunc()
}

// ByBedrooms orders the results by the bedrooms field.
func ByBedrooms(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBedrooms, opts...).ToFunc()
}

// ByBathrooms orders the results by the bathrooms field.
func ByBathrooms(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBathrooms, opts...).ToFunc()
}

// ByAreaSqm orders the results by the area_sqm field.
func ByAreaSqm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAreaSqm, opts...).ToFunc()
}

// ByLandAreaSqm orders the results by the land_area_sqm field.
func ByLandAreaSqm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLandAreaSqm, opts...).ToFunc()
}

// ByYearBuilt orders the results by the year_built field.
func ByYearBuilt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYearBuilt, opts...).ToFunc()
}

// ByFloor orders the results by the floor field.
func ByFloor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFloor, opts...).ToFunc()
}

// ByTotalFloors orders the results by the total_floors field.
func ByTotalFloors(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalFloors, opts...).ToFunc()
}

// ByParkingSpaces orders the results by the parking_spaces field.
func ByParkingSpaces(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParkingSpaces, opts...).ToFunc()
}

// ByHasGarage orders the results by the has_garage field.
func ByHasGarage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHasGarage, opts...).ToFunc()
}

// ByHasGarden orders the results by the has_garden field.
func ByHasGarden(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHasGarden, opts...).ToFunc()
}

// ByHasPool orders the results by the has_pool field.
func ByHasPool(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHasPool, opts...).ToFunc()
}

// ByHasElevator orders the results by the has_elevator field.
func ByHasElevator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHasElevator, opts...).ToFunc()
}

// ByEnergyRating orders the results by the energy_rating field.
func ByEnergyRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnergyRating, opts...).ToFunc()
}

// ByVirtualTourURL orders the results by the virtual_tour_url field.
func ByVirtualTourURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVirtualTourURL, opts...).ToFunc()
}

// ByContactID orders the results by the contact_id field.
func ByContactID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactID, opts...).ToFunc()
}

// ByPublisherID orders the results by the publisher_id field.
func ByPublisherID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublisherID, opts...).ToFunc()
}

// ByViewCount orders the results by the view_count field.
func ByViewCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViewCount, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPublisherField orders the results by publisher field.
func ByPublisherField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPublisherStep(), sql.OrderByField(field, opts...))
	}
}

// ByContactField orders the results by contact field.
func ByContactField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newContactStep(), sql.OrderByField(field, opts...))
	}
}

// ByImagesCount orders the results by images count.
func ByImagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newImagesStep(), opts...)
	}
}

// ByImages orders the results by images terms.
func ByImages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newImagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPublisherStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PublisherInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PublisherTable, PublisherColumn),
	)
}
func newContactStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ContactInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ContactTable, ContactColumn),
	)
}
func newImagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ImagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ImagesTable, ImagesColumn),
	)
}
