// Code generated by ent, DO NOT EDIT.

package userauth

import (
	"immo-lux/internal/database/ent/client/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldEQ(FieldUserID, v))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v string) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldEQ(FieldHash, v))
}

// PasswordChangedAt applies equality check predicate on the "password_changed_at" field. It's identical to PasswordChangedAtEQ.
func PasswordChangedAt(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldEQ(FieldPasswordChangedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldNotIn(FieldUserID, vs...))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v string) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v string) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...string) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...string) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v string) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v string) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v string) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v string) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldLTE(FieldHash, v))
}

// HashContains applies the Contains predicate on the "hash" field.
func HashContains(v string) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldContains(FieldHash, v))
}

// HashHasPrefix applies the HasPrefix predicate on the "hash" field.
func HashHasPrefix(v string) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldHasPrefix(FieldHash, v))
}

// HashHasSuffix applies the HasSuffix predicate on the "hash" field.
func HashHasSuffix(v string) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldHasSuffix(FieldHash, v))
}

// HashEqualFold applies the EqualFold predicate on the "hash" field.
func HashEqualFold(v string) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldEqualFold(FieldHash, v))
}

// HashContainsFold applies the ContainsFold predicate on the "hash" field.
func HashContainsFold(v string) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldContainsFold(FieldHash, v))
}

// PasswordChangedAtEQ applies the EQ predicate on the "password_changed_at" field.
func PasswordChangedAtEQ(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldEQ(FieldPasswordChangedAt, v))
}

// PasswordChangedAtNEQ applies the NEQ predicate on the "password_changed_at" field.
func PasswordChangedAtNEQ(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldNEQ(FieldPasswordChangedAt, v))
}

// PasswordChangedAtIn applies the In predicate on the "password_changed_at" field.
func PasswordChangedAtIn(vs ...time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldIn(FieldPasswordChangedAt, vs...))
}

// PasswordChangedAtNotIn applies the NotIn predicate on the "password_changed_at" field.
func PasswordChangedAtNotIn(vs ...time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldNotIn(FieldPasswordChangedAt, vs...))
}

// PasswordChangedAtGT applies the GT predicate on the "password_changed_at" field.
func PasswordChangedAtGT(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldGT(FieldPasswordChangedAt, v))
}

// PasswordChangedAtGTE applies the GTE predicate on the "password_changed_at" field.
func PasswordChangedAtGTE(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldGTE(FieldPasswordChangedAt, v))
}

// PasswordChangedAtLT applies the LT predicate on the "password_changed_at" field.
func PasswordChangedAtLT(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldLT(FieldPasswordChangedAt, v))
}

// PasswordChangedAtLTE applies the LTE predicate on the "password_changed_at" field.
func PasswordChangedAtLTE(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldLTE(FieldPasswordChangedAt, v))
}

// PasswordChangedAtIsNil applies the IsNil predicate on the "password_changed_at" field.
func PasswordChangedAtIsNil() predicate.UserAuth {
	return predicate.UserAuth(sql.FieldIsNull(FieldPasswordChangedAt))
}

// PasswordChangedAtNotNil applies the NotNil predicate on the "password_changed_at" field.
func PasswordChangedAtNotNil() predicate.UserAuth {
	return predicate.UserAuth(sql.FieldNotNull(FieldPasswordChangedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserAuth {
	return predicate.UserAuth(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserAuth {
	return predicate.UserAuth(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserAuth {
	return predicate.UserAuth(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserAuth) predicate.UserAuth {
	return predicate.UserAuth(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserAuth) predicate.UserAuth {
	return predicate.UserAuth(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserAuth) predicate.UserAuth {
	return predicate.UserAuth(sql.NotPredicates(p))
}
