// Code generated by ent, DO NOT EDIT.

package ratelimit

import (
	"immo-lux/internal/database/ent/client/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLTE(FieldID, id))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldEmail, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldIPAddress, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldAction, v))
}

// AttemptCount applies equality check predicate on the "attempt_count" field. It's identical to AttemptCountEQ.
func AttemptCount(v int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldAttemptCount, v))
}

// WindowStart applies equality check predicate on the "window_start" field. It's identical to WindowStartEQ.
func WindowStart(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldWindowStart, v))
}

// BlockedUntil applies equality check predicate on the "blocked_until" field. It's identical to BlockedUntilEQ.
func BlockedUntil(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldBlockedUntil, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldUpdatedAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldContainsFold(FieldEmail, v))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldContainsFold(FieldIPAddress, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldContainsFold(FieldAction, v))
}

// AttemptCountEQ applies the EQ predicate on the "attempt_count" field.
func AttemptCountEQ(v int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldAttemptCount, v))
}

// AttemptCountNEQ applies the NEQ predicate on the "attempt_count" field.
func AttemptCountNEQ(v int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNEQ(FieldAttemptCount, v))
}

// AttemptCountIn applies the In predicate on the "attempt_count" field.
func AttemptCountIn(vs ...int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldIn(FieldAttemptCount, vs...))
}

// AttemptCountNotIn applies the NotIn predicate on the "attempt_count" field.
func AttemptCountNotIn(vs ...int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNotIn(FieldAttemptCount, vs...))
}

// AttemptCountGT applies the GT predicate on the "attempt_count" field.
func AttemptCountGT(v int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGT(FieldAttemptCount, v))
}

// AttemptCountGTE applies the GTE predicate on the "attempt_count" field.
func AttemptCountGTE(v int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGTE(FieldAttemptCount, v))
}

// AttemptCountLT applies the LT predicate on the "attempt_count" field.
func AttemptCountLT(v int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLT(FieldAttemptCount, v))
}

// AttemptCountLTE applies the LTE predicate on the "attempt_count" field.
func AttemptCountLTE(v int) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLTE(FieldAttemptCount, v))
}

// WindowStartEQ applies the EQ predicate on the "window_start" field.
func WindowStartEQ(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldWindowStart, v))
}

// WindowStartNEQ applies the NEQ predicate on the "window_start" field.
func WindowStartNEQ(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNEQ(FieldWindowStart, v))
}

// WindowStartIn applies the In predicate on the "window_start" field.
func WindowStartIn(vs ...time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldIn(FieldWindowStart, vs...))
}

// WindowStartNotIn applies the NotIn predicate on the "window_start" field.
func WindowStartNotIn(vs ...time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNotIn(FieldWindowStart, vs...))
}

// WindowStartGT applies the GT predicate on the "window_start" field.
func WindowStartGT(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGT(FieldWindowStart, v))
}

// WindowStartGTE applies the GTE predicate on the "window_start" field.
func WindowStartGTE(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGTE(FieldWindowStart, v))
}

// WindowStartLT applies the LT predicate on the "window_start" field.
func WindowStartLT(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLT(FieldWindowStart, v))
}

// WindowStartLTE applies the LTE predicate on the "window_start" field.
func WindowStartLTE(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLTE(FieldWindowStart, v))
}

// BlockedUntilEQ applies the EQ predicate on the "blocked_until" field.
func BlockedUntilEQ(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldBlockedUntil, v))
}

// BlockedUntilNEQ applies the NEQ predicate on the "blocked_until" field.
func BlockedUntilNEQ(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNEQ(FieldBlockedUntil, v))
}

// BlockedUntilIn applies the In predicate on the "blocked_until" field.
func BlockedUntilIn(vs ...time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldIn(FieldBlockedUntil, vs...))
}

// BlockedUntilNotIn applies the NotIn predicate on the "blocked_until" field.
func BlockedUntilNotIn(vs ...time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNotIn(FieldBlockedUntil, vs...))
}

// BlockedUntilGT applies the GT predicate on the "blocked_until" field.
func BlockedUntilGT(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGT(FieldBlockedUntil, v))
}

// BlockedUntilGTE applies the GTE predicate on the "blocked_until" field.
func BlockedUntilGTE(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGTE(FieldBlockedUntil, v))
}

// BlockedUntilLT applies the LT predicate on the "blocked_until" field.
func BlockedUntilLT(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLT(FieldBlockedUntil, v))
}

// BlockedUntilLTE applies the LTE predicate on the "blocked_until" field.
func BlockedUntilLTE(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLTE(FieldBlockedUntil, v))
}

// BlockedUntilIsNil applies the IsNil predicate on the "blocked_until" field.
func BlockedUntilIsNil() predicate.RateLimit {
	return predicate.RateLimit(sql.FieldIsNull(FieldBlockedUntil))
}

// BlockedUntilNotNil applies the NotNil predicate on the "blocked_until" field.
func BlockedUntilNotNil() predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNotNull(FieldBlockedUntil))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RateLimit {
	return predicate.RateLimit(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RateLimit) predicate.RateLimit {
	return predicate.RateLimit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RateLimit) predicate.RateLimit {
	return predicate.RateLimit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RateLimit) predicate.RateLimit {
	return predicate.RateLimit(sql.NotPredicates(p))
}
