// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "session_token", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "invalidated_at", Type: field.TypeTime, Nullable: true},
		{Name: "invalidated_reason", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "ip_address", Type: field.TypeString, Nullable: true, Size: 45},
		{Name: "user_agent", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "session_user_id_is_active",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[10], SessionsColumns[2]},
			},
			{
				Name:    "session_session_token",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[1]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "first_name", Type: field.TypeString, Size: 100},
		{Name: "last_name", Type: field.TypeString, Size: 100},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[3]},
			},
		},
	}
	// UserAuthsColumns holds the columns for the "user_auths" table.
	UserAuthsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "hash", Type: field.TypeString},
		{Name: "is_locked", Type: field.TypeBool, Default: false},
		{Name: "locked_reason", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "failed_login_attempts", Type: field.TypeInt, Default: 0},
		{Name: "last_failed_attempt", Type: field.TypeTime, Nullable: true},
		{Name: "password_changed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt, Unique: true},
	}
	// UserAuthsTable holds the schema information for the "user_auths" table.
	UserAuthsTable = &schema.Table{
		Name:       "user_auths",
		Columns:    UserAuthsColumns,
		PrimaryKey: []*schema.Column{UserAuthsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_auths_users_auth",
				Columns:    []*schema.Column{UserAuthsColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userauth_user_id",
				Unique:  false,
				Columns: []*schema.Column{UserAuthsColumns[9]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SessionsTable,
		UsersTable,
		UserAuthsTable,
	}
)

func init() {
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
	UserAuthsTable.ForeignKeys[0].RefTable = UsersTable
}
