// Code generated by ent, DO NOT EDIT.

package client

import (
	"context"
	"errors"
	"fmt"
	"immo-lux/internal/database/ent/client/contact"
	"immo-lux/internal/database/ent/client/predicate"
	"immo-lux/internal/database/ent/client/property"
	"immo-lux/internal/database/ent/client/propertyimage"
	"immo-lux/internal/database/ent/client/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PropertyUpdate is the builder for updating Property entities.
type PropertyUpdate struct {
	config
	hooks    []Hook
	mutation *PropertyMutation
}

// Where appends a list predicates to the PropertyUpdate builder.
func (_u *PropertyUpdate) Where(ps ...predicate.Property) *PropertyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *PropertyUpdate) SetTitle(v string) *PropertyUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableTitle(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PropertyUpdate) SetDescription(v string) *PropertyUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableDescription(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPropertyType sets the "property_type" field.
func (_u *PropertyUpdate) SetPropertyType(v property.PropertyType) *PropertyUpdate {
	_u.mutation.SetPropertyType(v)
	return _u
}

// SetNillablePropertyType sets the "property_type" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillablePropertyType(v *property.PropertyType) *PropertyUpdate {
	if v != nil {
		_u.SetPropertyType(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *PropertyUpdate) SetPrice(v float64) *PropertyUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillablePrice(v *float64) *PropertyUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *PropertyUpdate) AddPrice(v float64) *PropertyUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PropertyUpdate) SetStatus(v property.Status) *PropertyUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableStatus(v *property.Status) *PropertyUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsPublished sets the "is_published" field.
func (_u *PropertyUpdate) SetIsPublished(v bool) *PropertyUpdate {
	_u.mutation.SetIsPublished(v)
	return _u
}

// SetNillableIsPublished sets the "is_published" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableIsPublished(v *bool) *PropertyUpdate {
	if v != nil {
		_u.SetIsPublished(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *PropertyUpdate) SetAddress(v string) *PropertyUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableAddress(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetDistrict sets the "district" field.
func (_u *PropertyUpdate) SetDistrict(v string) *PropertyUpdate {
	_u.mutation.SetDistrict(v)
	return _u
}

// SetNillableDistrict sets the "district" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableDistrict(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetDistrict(*v)
	}
	return _u
}

// SetMunicipality sets the "municipality" field.
func (_u *PropertyUpdate) SetMunicipality(v string) *PropertyUpdate {
	_u.mutation.SetMunicipality(v)
	return _u
}

// SetNillableMunicipality sets the "municipality" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableMunicipality(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetMunicipality(*v)
	}
	return _u
}

// SetParish sets the "parish" field.
func (_u *PropertyUpdate) SetParish(v string) *PropertyUpdate {
	_u.mutation.SetParish(v)
	return _u
}

// SetNillableParish sets the "parish" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableParish(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetParish(*v)
	}
	return _u
}

// ClearParish clears the value of the "parish" field.
func (_u *PropertyUpdate) ClearParish() *PropertyUpdate {
	_u.mutation.ClearParish()
	return _u
}

// SetPostalCode sets the "postal_code" field.
func (_u *PropertyUpdate) SetPostalCode(v string) *PropertyUpdate {
	_u.mutation.SetPostalCode(v)
	return _u
}

// SetNillablePostalCode sets the "postal_code" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillablePostalCode(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetPostalCode(*v)
	}
	return _u
}

// ClearPostalCode clears the value of the "postal_code" field.
func (_u *PropertyUpdate) ClearPostalCode() *PropertyUpdate {
	_u.mutation.ClearPostalCode()
	return _u
}

// SetCountry sets the "country" field.
func (_u *PropertyUpdate) SetCountry(v string) *PropertyUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableCountry(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *PropertyUpdate) SetLatitude(v float64) *PropertyUpdate {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableLatitude(v *float64) *PropertyUpdate {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *PropertyUpdate) AddLatitude(v float64) *PropertyUpdate {
	_u.mutation.AddLatitude(v)
	return _u
}

// ClearLatitude clears the value of the "latitude" field.
func (_u *PropertyUpdate) ClearLatitude() *PropertyUpdate {
	_u.mutation.ClearLatitude()
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *PropertyUpdate) SetLongitude(v float64) *PropertyUpdate {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableLongitude(v *float64) *PropertyUpdate {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *PropertyUpdate) AddLongitude(v float64) *PropertyUpdate {
	_u.mutation.AddLongitude(v)
	return _u
}

// ClearLongitude clears the value of the "longitude" field.
func (_u *PropertyUpdate) ClearLongitude() *PropertyUpdate {
	_u.mutation.ClearLongitude()
	return _u
}

// SetBedrooms sets the "bedrooms" field.
func (_u *PropertyUpdate) SetBedrooms(v int) *PropertyUpdate {
	_u.mutation.ResetBedrooms()
	_u.mutation.SetBedrooms(v)
	return _u
}

// SetNillableBedrooms sets the "bedrooms" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableBedrooms(v *int) *PropertyUpdate {
	if v != nil {
		_u.SetBedrooms(*v)
	}
	return _u
}

// AddBedrooms adds value to the "bedrooms" field.
func (_u *PropertyUpdate) AddBedrooms(v int) *PropertyUpdate {
	_u.mutation.AddBedrooms(v)
	return _u
}

// ClearBedrooms clears the value of the "bedrooms" field.
func (_u *PropertyUpdate) ClearBedrooms() *PropertyUpdate {
	_u.mutation.ClearBedrooms()
	return _u
}

// SetBathrooms sets the "bathrooms" field.
func (_u *PropertyUpdate) SetBathrooms(v int) *PropertyUpdate {
	_u.mutation.ResetBathrooms()
	_u.mutation.SetBathrooms(v)
	return _u
}

// SetNillableBathrooms sets the "bathrooms" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableBathrooms(v *int) *PropertyUpdate {
	if v != nil {
		_u.SetBathrooms(*v)
	}
	return _u
}

// AddBathrooms adds value to the "bathrooms" field.
func (_u *PropertyUpdate) AddBathrooms(v int) *PropertyUpdate {
	_u.mutation.AddBathrooms(v)
	return _u
}

// ClearBathrooms clears the value of the "bathrooms" field.
func (_u *PropertyUpdate) ClearBathrooms() *PropertyUpdate {
	_u.mutation.ClearBathrooms()
	return _u
}

// SetAreaSqm sets the "area_sqm" field.
func (_u *PropertyUpdate) SetAreaSqm(v float64) *PropertyUpdate {
	_u.mutation.ResetAreaSqm()
	_u.mutation.SetAreaSqm(v)
	return _u
}

// SetNillableAreaSqm sets the "area_sqm" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableAreaSqm(v *float64) *PropertyUpdate {
	if v != nil {
		_u.SetAreaSqm(*v)
	}
	return _u
}

// AddAreaSqm adds value to the "area_sqm" field.
func (_u *PropertyUpdate) AddAreaSqm(v float64) *PropertyUpdate {
	_u.mutation.AddAreaSqm(v)
	return _u
}

// ClearAreaSqm clears the value of the "area_sqm" field.
func (_u *PropertyUpdate) ClearAreaSqm() *PropertyUpdate {
	_u.mutation.ClearAreaSqm()
	return _u
}

// SetLandAreaSqm sets the "land_area_sqm" field.
func (_u *PropertyUpdate) SetLandAreaSqm(v float64) *PropertyUpdate {
	_u.mutation.ResetLandAreaSqm()
	_u.mutation.SetLandAreaSqm(v)
	return _u
}

// SetNillableLandAreaSqm sets the "land_area_sqm" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableLandAreaSqm(v *float64) *PropertyUpdate {
	if v != nil {
		_u.SetLandAreaSqm(*v)
	}
	return _u
}

// AddLandAreaSqm adds value to the "land_area_sqm" field.
func (_u *PropertyUpdate) AddLandAreaSqm(v float64) *PropertyUpdate {
	_u.mutation.AddLandAreaSqm(v)
	return _u
}

// ClearLandAreaSqm clears the value of the "land_area_sqm" field.
func (_u *PropertyUpdate) ClearLandAreaSqm() *PropertyUpdate {
	_u.mutation.ClearLandAreaSqm()
	return _u
}

// SetYearBuilt sets the "year_built" field.
func (_u *PropertyUpdate) SetYearBuilt(v int) *PropertyUpdate {
	_u.mutation.ResetYearBuilt()
	_u.mutation.SetYearBuilt(v)
	return _u
}

// SetNillableYearBuilt sets the "year_built" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableYearBuilt(v *int) *PropertyUpdate {
	if v != nil {
		_u.SetYearBuilt(*v)
	}
	return _u
}

// AddYearBuilt adds value to the "year_built" field.
func (_u *PropertyUpdate) AddYearBuilt(v int) *PropertyUpdate {
	_u.mutation.AddYearBuilt(v)
	return _u
}

// ClearYearBuilt clears the value of the "year_built" field.
func (_u *PropertyUpdate) ClearYearBuilt() *PropertyUpdate {
	_u.mutation.ClearYearBuilt()
	return _u
}

// SetFloor sets the "floor" field.
func (_u *PropertyUpdate) SetFloor(v int) *PropertyUpdate {
	_u.mutation.ResetFloor()
	_u.mutation.SetFloor(v)
	return _u
}

// SetNillableFloor sets the "floor" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableFloor(v *int) *PropertyUpdate {
	if v != nil {
		_u.SetFloor(*v)
	}
	return _u
}

// AddFloor adds value to the "floor" field.
func (_u *PropertyUpdate) AddFloor(v int) *PropertyUpdate {
	_u.mutation.AddFloor(v)
	return _u
}

// ClearFloor clears the value of the "floor" field.
func (_u *PropertyUpdate) ClearFloor() *PropertyUpdate {
	_u.mutation.ClearFloor()
	return _u
}

// SetTotalFloors sets the "total_floors" field.
func (_u *PropertyUpdate) SetTotalFloors(v int) *PropertyUpdate {
	_u.mutation.ResetTotalFloors()
	_u.mutation.SetTotalFloors(v)
	return _u
}

// SetNillableTotalFloors sets the "total_floors" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableTotalFloors(v *int) *PropertyUpdate {
	if v != nil {
		_u.SetTotalFloors(*v)
	}
	return _u
}

// AddTotalFloors adds value to the "total_floors" field.
func (_u *PropertyUpdate) AddTotalFloors(v int) *PropertyUpdate {
	_u.mutation.AddTotalFloors(v)
	return _u
}

// ClearTotalFloors clears the value of the "total_floors" field.
func (_u *PropertyUpdate) ClearTotalFloors() *PropertyUpdate {
	_u.mutation.ClearTotalFloors()
	return _u
}

// SetParkingSpaces sets the "parking_spaces" field.
func (_u *PropertyUpdate) SetParkingSpaces(v int) *PropertyUpdate {
	_u.mutation.ResetParkingSpaces()
	_u.mutation.SetParkingSpaces(v)
	return _u
}

// SetNillableParkingSpaces sets the "parking_spaces" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableParkingSpaces(v *int) *PropertyUpdate {
	if v != nil {
		_u.SetParkingSpaces(*v)
	}
	return _u
}

// AddParkingSpaces adds value to the "parking_spaces" field.
func (_u *PropertyUpdate) AddParkingSpaces(v int) *PropertyUpdate {
	_u.mutation.AddParkingSpaces(v)
	return _u
}

// ClearParkingSpaces clears the value of the "parking_spaces" field.
func (_u *PropertyUpdate) ClearParkingSpaces() *PropertyUpdate {
	_u.mutation.ClearParkingSpaces()
	return _u
}

// SetHasGarage sets the "has_garage" field.
func (_u *PropertyUpdate) SetHasGarage(v bool) *PropertyUpdate {
	_u.mutation.SetHasGarage(v)
	return _u
}

// SetNillableHasGarage sets the "has_garage" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableHasGarage(v *bool) *PropertyUpdate {
	if v != nil {
		_u.SetHasGarage(*v)
	}
	return _u
}

// SetHasGarden sets the "has_garden" field.
func (_u *PropertyUpdate) SetHasGarden(v bool) *PropertyUpdate {
	_u.mutation.SetHasGarden(v)
	return _u
}

// SetNillableHasGarden sets the "has_garden" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableHasGarden(v *bool) *PropertyUpdate {
	if v != nil {
		_u.SetHasGarden(*v)
	}
	return _u
}

// SetHasPool sets the "has_pool" field.
func (_u *PropertyUpdate) SetHasPool(v bool) *PropertyUpdate {
	_u.mutation.SetHasPool(v)
	return _u
}

// SetNillableHasPool sets the "has_pool" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableHasPool(v *bool) *PropertyUpdate {
	if v != nil {
		_u.SetHasPool(*v)
	}
	return _u
}

// SetHasElevator sets the "has_elevator" field.
func (_u *PropertyUpdate) SetHasElevator(v bool) *PropertyUpdate {
	_u.mutation.SetHasElevator(v)
	return _u
}

// SetNillableHasElevator sets the "has_elevator" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableHasElevator(v *bool) *PropertyUpdate {
	if v != nil {
		_u.SetHasElevator(*v)
	}
	return _u
}

// SetEnergyRating sets the "energy_rating" field.
func (_u *PropertyUpdate) SetEnergyRating(v property.EnergyRating) *PropertyUpdate {
	_u.mutation.SetEnergyRating(v)
	return _u
}

// SetNillableEnergyRating sets the "energy_rating" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableEnergyRating(v *property.EnergyRating) *PropertyUpdate {
	if v != nil {
		_u.SetEnergyRating(*v)
	}
	return _u
}

// ClearEnergyRating clears the value of the "energy_rating" field.
func (_u *PropertyUpdate) ClearEnergyRating() *PropertyUpdate {
	_u.mutation.ClearEnergyRating()
	return _u
}

// SetVirtualTourURL sets the "virtual_tour_url" field.
func (_u *PropertyUpdate) SetVirtualTourURL(v string) *PropertyUpdate {
	_u.mutation.SetVirtualTourURL(v)
	return _u
}

// SetNillableVirtualTourURL sets the "virtual_tour_url" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableVirtualTourURL(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetVirtualTourURL(*v)
	}
	return _u
}

// ClearVirtualTourURL clears the value of the "virtual_tour_url" field.
func (_u *PropertyUpdate) ClearVirtualTourURL() *PropertyUpdate {
	_u.mutation.ClearVirtualTourURL()
	return _u
}

// SetPublisherID sets the "publisher_id" field.
func (_u *PropertyUpdate) SetPublisherID(v int) *PropertyUpdate {
	_u.mutation.SetPublisherID(v)
	return _u
}

// SetNillablePublisherID sets the "publisher_id" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillablePublisherID(v *int) *PropertyUpdate {
	if v != nil {
		_u.SetPublisherID(*v)
	}
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *PropertyUpdate) SetViewCount(v int) *PropertyUpdate {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableViewCount(v *int) *PropertyUpdate {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *PropertyUpdate) AddViewCount(v int) *PropertyUpdate {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PropertyUpdate) SetPublishedAt(v time.Time) *PropertyUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillablePublishedAt(v *time.Time) *PropertyUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *PropertyUpdate) ClearPublishedAt() *PropertyUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PropertyUpdate) SetUpdatedAt(v time.Time) *PropertyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublisher sets the "publisher" edge to the User entity.
func (_u *PropertyUpdate) SetPublisher(v *User) *PropertyUpdate {
	return _u.SetPublisherID(v.ID)
}

// AddContactIDs adds the "contacts" edge to the Contact entity by IDs.
func (_u *PropertyUpdate) AddContactIDs(ids ...int) *PropertyUpdate {
	_u.mutation.AddContactIDs(ids...)
	return _u
}

// AddContacts adds the "contacts" edges to the Contact entity.
func (_u *PropertyUpdate) AddContacts(v ...*Contact) *PropertyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContactIDs(ids...)
}

// AddImageIDs adds the "images" edge to the PropertyImage entity by IDs.
func (_u *PropertyUpdate) AddImageIDs(ids ...int) *PropertyUpdate {
	_u.mutation.AddImageIDs(ids...)
	return _u
}

// AddImages adds the "images" edges to the PropertyImage entity.
func (_u *PropertyUpdate) AddImages(v ...*PropertyImage) *PropertyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddImageIDs(ids...)
}

// Mutation returns the PropertyMutation object of the builder.
func (_u *PropertyUpdate) Mutation() *PropertyMutation {
	return _u.mutation
}

// ClearPublisher clears the "publisher" edge to the User entity.
func (_u *PropertyUpdate) ClearPublisher() *PropertyUpdate {
	_u.mutation.ClearPublisher()
	return _u
}

// ClearContacts clears all "contacts" edges to the Contact entity.
func (_u *PropertyUpdate) ClearContacts() *PropertyUpdate {
	_u.mutation.ClearContacts()
	return _u
}

// RemoveContactIDs removes the "contacts" edge to Contact entities by IDs.
func (_u *PropertyUpdate) RemoveContactIDs(ids ...int) *PropertyUpdate {
	_u.mutation.RemoveContactIDs(ids...)
	return _u
}

// RemoveContacts removes "contacts" edges to Contact entities.
func (_u *PropertyUpdate) RemoveContacts(v ...*Contact) *PropertyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContactIDs(ids...)
}

// ClearImages clears all "images" edges to the PropertyImage entity.
func (_u *PropertyUpdate) ClearImages() *PropertyUpdate {
	_u.mutation.ClearImages()
	return _u
}

// RemoveImageIDs removes the "images" edge to PropertyImage entities by IDs.
func (_u *PropertyUpdate) RemoveImageIDs(ids ...int) *PropertyUpdate {
	_u.mutation.RemoveImageIDs(ids...)
	return _u
}

// RemoveImages removes "images" edges to PropertyImage entities.
func (_u *PropertyUpdate) RemoveImages(v ...*PropertyImage) *PropertyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveImageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PropertyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PropertyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PropertyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PropertyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PropertyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := property.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PropertyUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := property.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`client: validator failed for field "Property.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := property.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`client: validator failed for field "Property.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PropertyType(); ok {
		if err := property.PropertyTypeValidator(v); err != nil {
			return &ValidationError{Name: "property_type", err: fmt.Errorf(`client: validator failed for field "Property.property_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Price(); ok {
		if err := property.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`client: validator failed for field "Property.price": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := property.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`client: validator failed for field "Property.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := property.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`client: validator failed for field "Property.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.District(); ok {
		if err := property.DistrictValidator(v); err != nil {
			return &ValidationError{Name: "district", err: fmt.Errorf(`client: validator failed for field "Property.district": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Municipality(); ok {
		if err := property.MunicipalityValidator(v); err != nil {
			return &ValidationError{Name: "municipality", err: fmt.Errorf(`client: validator failed for field "Property.municipality": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Parish(); ok {
		if err := property.ParishValidator(v); err != nil {
			return &ValidationError{Name: "parish", err: fmt.Errorf(`client: validator failed for field "Property.parish": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PostalCode(); ok {
		if err := property.PostalCodeValidator(v); err != nil {
			return &ValidationError{Name: "postal_code", err: fmt.Errorf(`client: validator failed for field "Property.postal_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := property.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`client: validator failed for field "Property.country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bedrooms(); ok {
		if err := property.BedroomsValidator(v); err != nil {
			return &ValidationError{Name: "bedrooms", err: fmt.Errorf(`client: validator failed for field "Property.bedrooms": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bathrooms(); ok {
		if err := property.BathroomsValidator(v); err != nil {
			return &ValidationError{Name: "bathrooms", err: fmt.Errorf(`client: validator failed for field "Property.bathrooms": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AreaSqm(); ok {
		if err := property.AreaSqmValidator(v); err != nil {
			return &ValidationError{Name: "area_sqm", err: fmt.Errorf(`client: validator failed for field "Property.area_sqm": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LandAreaSqm(); ok {
		if err := property.LandAreaSqmValidator(v); err != nil {
			return &ValidationError{Name: "land_area_sqm", err: fmt.Errorf(`client: validator failed for field "Property.land_area_sqm": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ParkingSpaces(); ok {
		if err := property.ParkingSpacesValidator(v); err != nil {
			return &ValidationError{Name: "parking_spaces", err: fmt.Errorf(`client: validator failed for field "Property.parking_spaces": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EnergyRating(); ok {
		if err := property.EnergyRatingValidator(v); err != nil {
			return &ValidationError{Name: "energy_rating", err: fmt.Errorf(`client: validator failed for field "Property.energy_rating": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VirtualTourURL(); ok {
		if err := property.VirtualTourURLValidator(v); err != nil {
			return &ValidationError{Name: "virtual_tour_url", err: fmt.Errorf(`client: validator failed for field "Property.virtual_tour_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublisherID(); ok {
		if err := property.PublisherIDValidator(v); err != nil {
			return &ValidationError{Name: "publisher_id", err: fmt.Errorf(`client: validator failed for field "Property.publisher_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ViewCount(); ok {
		if err := property.ViewCountValidator(v); err != nil {
			return &ValidationError{Name: "view_count", err: fmt.Errorf(`client: validator failed for field "Property.view_count": %w`, err)}
		}
	}
	if _u.mutation.PublisherCleared() && len(_u.mutation.PublisherIDs()) > 0 {
		return errors.New(`client: clearing a required unique edge "Property.publisher"`)
	}
	return nil
}

func (_u *PropertyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(property.Table, property.Columns, sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(property.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(property.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.PropertyType(); ok {
		_spec.SetField(property.FieldPropertyType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(property.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(property.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(property.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsPublished(); ok {
		_spec.SetField(property.FieldIsPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(property.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.District(); ok {
		_spec.SetField(property.FieldDistrict, field.TypeString, value)
	}
	if value, ok := _u.mutation.Municipality(); ok {
		_spec.SetField(property.FieldMunicipality, field.TypeString, value)
	}
	if value, ok := _u.mutation.Parish(); ok {
		_spec.SetField(property.FieldParish, field.TypeString, value)
	}
	if _u.mutation.ParishCleared() {
		_spec.ClearField(property.FieldParish, field.TypeString)
	}
	if value, ok := _u.mutation.PostalCode(); ok {
		_spec.SetField(property.FieldPostalCode, field.TypeString, value)
	}
	if _u.mutation.PostalCodeCleared() {
		_spec.ClearField(property.FieldPostalCode, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(property.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(property.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(property.FieldLatitude, field.TypeFloat64, value)
	}
	if _u.mutation.LatitudeCleared() {
		_spec.ClearField(property.FieldLatitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(property.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(property.FieldLongitude, field.TypeFloat64, value)
	}
	if _u.mutation.LongitudeCleared() {
		_spec.ClearField(property.FieldLongitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Bedrooms(); ok {
		_spec.SetField(property.FieldBedrooms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBedrooms(); ok {
		_spec.AddField(property.FieldBedrooms, field.TypeInt, value)
	}
	if _u.mutation.BedroomsCleared() {
		_spec.ClearField(property.FieldBedrooms, field.TypeInt)
	}
	if value, ok := _u.mutation.Bathrooms(); ok {
		_spec.SetField(property.FieldBathrooms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBathrooms(); ok {
		_spec.AddField(property.FieldBathrooms, field.TypeInt, value)
	}
	if _u.mutation.BathroomsCleared() {
		_spec.ClearField(property.FieldBathrooms, field.TypeInt)
	}
	if value, ok := _u.mutation.AreaSqm(); ok {
		_spec.SetField(property.FieldAreaSqm, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAreaSqm(); ok {
		_spec.AddField(property.FieldAreaSqm, field.TypeFloat64, value)
	}
	if _u.mutation.AreaSqmCleared() {
		_spec.ClearField(property.FieldAreaSqm, field.TypeFloat64)
	}
	if value, ok := _u.mutation.LandAreaSqm(); ok {
		_spec.SetField(property.FieldLandAreaSqm, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLandAreaSqm(); ok {
		_spec.AddField(property.FieldLandAreaSqm, field.TypeFloat64, value)
	}
	if _u.mutation.LandAreaSqmCleared() {
		_spec.ClearField(property.FieldLandAreaSqm, field.TypeFloat64)
	}
	if value, ok := _u.mutation.YearBuilt(); ok {
		_spec.SetField(property.FieldYearBuilt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYearBuilt(); ok {
		_spec.AddField(property.FieldYearBuilt, field.TypeInt, value)
	}
	if _u.mutation.YearBuiltCleared() {
		_spec.ClearField(property.FieldYearBuilt, field.TypeInt)
	}
	if value, ok := _u.mutation.Floor(); ok {
		_spec.SetField(property.FieldFloor, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFloor(); ok {
		_spec.AddField(property.FieldFloor, field.TypeInt, value)
	}
	if _u.mutation.FloorCleared() {
		_spec.ClearField(property.FieldFloor, field.TypeInt)
	}
	if value, ok := _u.mutation.TotalFloors(); ok {
		_spec.SetField(property.FieldTotalFloors, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalFloors(); ok {
		_spec.AddField(property.FieldTotalFloors, field.TypeInt, value)
	}
	if _u.mutation.TotalFloorsCleared() {
		_spec.ClearField(property.FieldTotalFloors, field.TypeInt)
	}
	if value, ok := _u.mutation.ParkingSpaces(); ok {
		_spec.SetField(property.FieldParkingSpaces, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParkingSpaces(); ok {
		_spec.AddField(property.FieldParkingSpaces, field.TypeInt, value)
	}
	if _u.mutation.ParkingSpacesCleared() {
		_spec.ClearField(property.FieldParkingSpaces, field.TypeInt)
	}
	if value, ok := _u.mutation.HasGarage(); ok {
		_spec.SetField(property.FieldHasGarage, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HasGarden(); ok {
		_spec.SetField(property.FieldHasGarden, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HasPool(); ok {
		_spec.SetField(property.FieldHasPool, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HasElevator(); ok {
		_spec.SetField(property.FieldHasElevator, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnergyRating(); ok {
		_spec.SetField(property.FieldEnergyRating, field.TypeEnum, value)
	}
	if _u.mutation.EnergyRatingCleared() {
		_spec.ClearField(property.FieldEnergyRating, field.TypeEnum)
	}
	if value, ok := _u.mutation.VirtualTourURL(); ok {
		_spec.SetField(property.FieldVirtualTourURL, field.TypeString, value)
	}
	if _u.mutation.VirtualTourURLCleared() {
		_spec.ClearField(property.FieldVirtualTourURL, field.TypeString)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(property.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(property.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(property.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(property.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(property.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PublisherCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   property.PublisherTable,
			Columns: []string{property.PublisherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PublisherIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   property.PublisherTable,
			Columns: []string{property.PublisherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContactsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   property.ContactsTable,
			Columns: property.ContactsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContactsIDs(); len(nodes) > 0 && !_u.mutation.ContactsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   property.ContactsTable,
			Columns: property.ContactsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContactsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   property.ContactsTable,
			Columns: property.ContactsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   property.ImagesTable,
			Columns: []string{property.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertyimage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedImagesIDs(); len(nodes) > 0 && !_u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   property.ImagesTable,
			Columns: []string{property.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertyimage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ImagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   property.ImagesTable,
			Columns: []string{property.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertyimage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{property.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PropertyUpdateOne is the builder for updating a single Property entity.
type PropertyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PropertyMutation
}

// SetTitle sets the "title" field.
func (_u *PropertyUpdateOne) SetTitle(v string) *PropertyUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableTitle(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PropertyUpdateOne) SetDescription(v string) *PropertyUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableDescription(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPropertyType sets the "property_type" field.
func (_u *PropertyUpdateOne) SetPropertyType(v property.PropertyType) *PropertyUpdateOne {
	_u.mutation.SetPropertyType(v)
	return _u
}

// SetNillablePropertyType sets the "property_type" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillablePropertyType(v *property.PropertyType) *PropertyUpdateOne {
	if v != nil {
		_u.SetPropertyType(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *PropertyUpdateOne) SetPrice(v float64) *PropertyUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillablePrice(v *float64) *PropertyUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *PropertyUpdateOne) AddPrice(v float64) *PropertyUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PropertyUpdateOne) SetStatus(v property.Status) *PropertyUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableStatus(v *property.Status) *PropertyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsPublished sets the "is_published" field.
func (_u *PropertyUpdateOne) SetIsPublished(v bool) *PropertyUpdateOne {
	_u.mutation.SetIsPublished(v)
	return _u
}

// SetNillableIsPublished sets the "is_published" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableIsPublished(v *bool) *PropertyUpdateOne {
	if v != nil {
		_u.SetIsPublished(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *PropertyUpdateOne) SetAddress(v string) *PropertyUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableAddress(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetDistrict sets the "district" field.
func (_u *PropertyUpdateOne) SetDistrict(v string) *PropertyUpdateOne {
	_u.mutation.SetDistrict(v)
	return _u
}

// SetNillableDistrict sets the "district" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableDistrict(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetDistrict(*v)
	}
	return _u
}

// SetMunicipality sets the "municipality" field.
func (_u *PropertyUpdateOne) SetMunicipality(v string) *PropertyUpdateOne {
	_u.mutation.SetMunicipality(v)
	return _u
}

// SetNillableMunicipality sets the "municipality" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableMunicipality(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetMunicipality(*v)
	}
	return _u
}

// SetParish sets the "parish" field.
func (_u *PropertyUpdateOne) SetParish(v string) *PropertyUpdateOne {
	_u.mutation.SetParish(v)
	return _u
}

// SetNillableParish sets the "parish" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableParish(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetParish(*v)
	}
	return _u
}

// ClearParish clears the value of the "parish" field.
func (_u *PropertyUpdateOne) ClearParish() *PropertyUpdateOne {
	_u.mutation.ClearParish()
	return _u
}

// SetPostalCode sets the "postal_code" field.
func (_u *PropertyUpdateOne) SetPostalCode(v string) *PropertyUpdateOne {
	_u.mutation.SetPostalCode(v)
	return _u
}

// SetNillablePostalCode sets the "postal_code" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillablePostalCode(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetPostalCode(*v)
	}
	return _u
}

// ClearPostalCode clears the value of the "postal_code" field.
func (_u *PropertyUpdateOne) ClearPostalCode() *PropertyUpdateOne {
	_u.mutation.ClearPostalCode()
	return _u
}

// SetCountry sets the "country" field.
func (_u *PropertyUpdateOne) SetCountry(v string) *PropertyUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableCountry(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *PropertyUpdateOne) SetLatitude(v float64) *PropertyUpdateOne {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableLatitude(v *float64) *PropertyUpdateOne {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *PropertyUpdateOne) AddLatitude(v float64) *PropertyUpdateOne {
	_u.mutation.AddLatitude(v)
	return _u
}

// ClearLatitude clears the value of the "latitude" field.
func (_u *PropertyUpdateOne) ClearLatitude() *PropertyUpdateOne {
	_u.mutation.ClearLatitude()
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *PropertyUpdateOne) SetLongitude(v float64) *PropertyUpdateOne {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableLongitude(v *float64) *PropertyUpdateOne {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *PropertyUpdateOne) AddLongitude(v float64) *PropertyUpdateOne {
	_u.mutation.AddLongitude(v)
	return _u
}

// ClearLongitude clears the value of the "longitude" field.
func (_u *PropertyUpdateOne) ClearLongitude() *PropertyUpdateOne {
	_u.mutation.ClearLongitude()
	return _u
}

// SetBedrooms sets the "bedrooms" field.
func (_u *PropertyUpdateOne) SetBedrooms(v int) *PropertyUpdateOne {
	_u.mutation.ResetBedrooms()
	_u.mutation.SetBedrooms(v)
	return _u
}

// SetNillableBedrooms sets the "bedrooms" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableBedrooms(v *int) *PropertyUpdateOne {
	if v != nil {
		_u.SetBedrooms(*v)
	}
	return _u
}

// AddBedrooms adds value to the "bedrooms" field.
func (_u *PropertyUpdateOne) AddBedrooms(v int) *PropertyUpdateOne {
	_u.mutation.AddBedrooms(v)
	return _u
}

// ClearBedrooms clears the value of the "bedrooms" field.
func (_u *PropertyUpdateOne) ClearBedrooms() *PropertyUpdateOne {
	_u.mutation.ClearBedrooms()
	return _u
}

// SetBathrooms sets the "bathrooms" field.
func (_u *PropertyUpdateOne) SetBathrooms(v int) *PropertyUpdateOne {
	_u.mutation.ResetBathrooms()
	_u.mutation.SetBathrooms(v)
	return _u
}

// SetNillableBathrooms sets the "bathrooms" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableBathrooms(v *int) *PropertyUpdateOne {
	if v != nil {
		_u.SetBathrooms(*v)
	}
	return _u
}

// AddBathrooms adds value to the "bathrooms" field.
func (_u *PropertyUpdateOne) AddBathrooms(v int) *PropertyUpdateOne {
	_u.mutation.AddBathrooms(v)
	return _u
}

// ClearBathrooms clears the value of the "bathrooms" field.
func (_u *PropertyUpdateOne) ClearBathrooms() *PropertyUpdateOne {
	_u.mutation.ClearBathrooms()
	return _u
}

// SetAreaSqm sets the "area_sqm" field.
func (_u *PropertyUpdateOne) SetAreaSqm(v float64) *PropertyUpdateOne {
	_u.mutation.ResetAreaSqm()
	_u.mutation.SetAreaSqm(v)
	return _u
}

// SetNillableAreaSqm sets the "area_sqm" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableAreaSqm(v *float64) *PropertyUpdateOne {
	if v != nil {
		_u.SetAreaSqm(*v)
	}
	return _u
}

// AddAreaSqm adds value to the "area_sqm" field.
func (_u *PropertyUpdateOne) AddAreaSqm(v float64) *PropertyUpdateOne {
	_u.mutation.AddAreaSqm(v)
	return _u
}

// ClearAreaSqm clears the value of the "area_sqm" field.
func (_u *PropertyUpdateOne) ClearAreaSqm() *PropertyUpdateOne {
	_u.mutation.ClearAreaSqm()
	return _u
}

// SetLandAreaSqm sets the "land_area_sqm" field.
func (_u *PropertyUpdateOne) SetLandAreaSqm(v float64) *PropertyUpdateOne {
	_u.mutation.ResetLandAreaSqm()
	_u.mutation.SetLandAreaSqm(v)
	return _u
}

// SetNillableLandAreaSqm sets the "land_area_sqm" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableLandAreaSqm(v *float64) *PropertyUpdateOne {
	if v != nil {
		_u.SetLandAreaSqm(*v)
	}
	return _u
}

// AddLandAreaSqm adds value to the "land_area_sqm" field.
func (_u *PropertyUpdateOne) AddLandAreaSqm(v float64) *PropertyUpdateOne {
	_u.mutation.AddLandAreaSqm(v)
	return _u
}

// ClearLandAreaSqm clears the value of the "land_area_sqm" field.
func (_u *PropertyUpdateOne) ClearLandAreaSqm() *PropertyUpdateOne {
	_u.mutation.ClearLandAreaSqm()
	return _u
}

// SetYearBuilt sets the "year_built" field.
func (_u *PropertyUpdateOne) SetYearBuilt(v int) *PropertyUpdateOne {
	_u.mutation.ResetYearBuilt()
	_u.mutation.SetYearBuilt(v)
	return _u
}

// SetNillableYearBuilt sets the "year_built" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableYearBuilt(v *int) *PropertyUpdateOne {
	if v != nil {
		_u.SetYearBuilt(*v)
	}
	return _u
}

// AddYearBuilt adds value to the "year_built" field.
func (_u *PropertyUpdateOne) AddYearBuilt(v int) *PropertyUpdateOne {
	_u.mutation.AddYearBuilt(v)
	return _u
}

// ClearYearBuilt clears the value of the "year_built" field.
func (_u *PropertyUpdateOne) ClearYearBuilt() *PropertyUpdateOne {
	_u.mutation.ClearYearBuilt()
	return _u
}

// SetFloor sets the "floor" field.
func (_u *PropertyUpdateOne) SetFloor(v int) *PropertyUpdateOne {
	_u.mutation.ResetFloor()
	_u.mutation.SetFloor(v)
	return _u
}

// SetNillableFloor sets the "floor" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableFloor(v *int) *PropertyUpdateOne {
	if v != nil {
		_u.SetFloor(*v)
	}
	return _u
}

// AddFloor adds value to the "floor" field.
func (_u *PropertyUpdateOne) AddFloor(v int) *PropertyUpdateOne {
	_u.mutation.AddFloor(v)
	return _u
}

// ClearFloor clears the value of the "floor" field.
func (_u *PropertyUpdateOne) ClearFloor() *PropertyUpdateOne {
	_u.mutation.ClearFloor()
	return _u
}

// SetTotalFloors sets the "total_floors" field.
func (_u *PropertyUpdateOne) SetTotalFloors(v int) *PropertyUpdateOne {
	_u.mutation.ResetTotalFloors()
	_u.mutation.SetTotalFloors(v)
	return _u
}

// SetNillableTotalFloors sets the "total_floors" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableTotalFloors(v *int) *PropertyUpdateOne {
	if v != nil {
		_u.SetTotalFloors(*v)
	}
	return _u
}

// AddTotalFloors adds value to the "total_floors" field.
func (_u *PropertyUpdateOne) AddTotalFloors(v int) *PropertyUpdateOne {
	_u.mutation.AddTotalFloors(v)
	return _u
}

// ClearTotalFloors clears the value of the "total_floors" field.
func (_u *PropertyUpdateOne) ClearTotalFloors() *PropertyUpdateOne {
	_u.mutation.ClearTotalFloors()
	return _u
}

// SetParkingSpaces sets the "parking_spaces" field.
func (_u *PropertyUpdateOne) SetParkingSpaces(v int) *PropertyUpdateOne {
	_u.mutation.ResetParkingSpaces()
	_u.mutation.SetParkingSpaces(v)
	return _u
}

// SetNillableParkingSpaces sets the "parking_spaces" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableParkingSpaces(v *int) *PropertyUpdateOne {
	if v != nil {
		_u.SetParkingSpaces(*v)
	}
	return _u
}

// AddParkingSpaces adds value to the "parking_spaces" field.
func (_u *PropertyUpdateOne) AddParkingSpaces(v int) *PropertyUpdateOne {
	_u.mutation.AddParkingSpaces(v)
	return _u
}

// ClearParkingSpaces clears the value of the "parking_spaces" field.
func (_u *PropertyUpdateOne) ClearParkingSpaces() *PropertyUpdateOne {
	_u.mutation.ClearParkingSpaces()
	return _u
}

// SetHasGarage sets the "has_garage" field.
func (_u *PropertyUpdateOne) SetHasGarage(v bool) *PropertyUpdateOne {
	_u.mutation.SetHasGarage(v)
	return _u
}

// SetNillableHasGarage sets the "has_garage" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableHasGarage(v *bool) *PropertyUpdateOne {
	if v != nil {
		_u.SetHasGarage(*v)
	}
	return _u
}

// SetHasGarden sets the "has_garden" field.
func (_u *PropertyUpdateOne) SetHasGarden(v bool) *PropertyUpdateOne {
	_u.mutation.SetHasGarden(v)
	return _u
}

// SetNillableHasGarden sets the "has_garden" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableHasGarden(v *bool) *PropertyUpdateOne {
	if v != nil {
		_u.SetHasGarden(*v)
	}
	return _u
}

// SetHasPool sets the "has_pool" field.
func (_u *PropertyUpdateOne) SetHasPool(v bool) *PropertyUpdateOne {
	_u.mutation.SetHasPool(v)
	return _u
}

// SetNillableHasPool sets the "has_pool" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableHasPool(v *bool) *PropertyUpdateOne {
	if v != nil {
		_u.SetHasPool(*v)
	}
	return _u
}

// SetHasElevator sets the "has_elevator" field.
func (_u *PropertyUpdateOne) SetHasElevator(v bool) *PropertyUpdateOne {
	_u.mutation.SetHasElevator(v)
	return _u
}

// SetNillableHasElevator sets the "has_elevator" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableHasElevator(v *bool) *PropertyUpdateOne {
	if v != nil {
		_u.SetHasElevator(*v)
	}
	return _u
}

// SetEnergyRating sets the "energy_rating" field.
func (_u *PropertyUpdateOne) SetEnergyRating(v property.EnergyRating) *PropertyUpdateOne {
	_u.mutation.SetEnergyRating(v)
	return _u
}

// SetNillableEnergyRating sets the "energy_rating" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableEnergyRating(v *property.EnergyRating) *PropertyUpdateOne {
	if v != nil {
		_u.SetEnergyRating(*v)
	}
	return _u
}

// ClearEnergyRating clears the value of the "energy_rating" field.
func (_u *PropertyUpdateOne) ClearEnergyRating() *PropertyUpdateOne {
	_u.mutation.ClearEnergyRating()
	return _u
}

// SetVirtualTourURL sets the "virtual_tour_url" field.
func (_u *PropertyUpdateOne) SetVirtualTourURL(v string) *PropertyUpdateOne {
	_u.mutation.SetVirtualTourURL(v)
	return _u
}

// SetNillableVirtualTourURL sets the "virtual_tour_url" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableVirtualTourURL(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetVirtualTourURL(*v)
	}
	return _u
}

// ClearVirtualTourURL clears the value of the "virtual_tour_url" field.
func (_u *PropertyUpdateOne) ClearVirtualTourURL() *PropertyUpdateOne {
	_u.mutation.ClearVirtualTourURL()
	return _u
}

// SetPublisherID sets the "publisher_id" field.
func (_u *PropertyUpdateOne) SetPublisherID(v int) *PropertyUpdateOne {
	_u.mutation.SetPublisherID(v)
	return _u
}

// SetNillablePublisherID sets the "publisher_id" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillablePublisherID(v *int) *PropertyUpdateOne {
	if v != nil {
		_u.SetPublisherID(*v)
	}
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *PropertyUpdateOne) SetViewCount(v int) *PropertyUpdateOne {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableViewCount(v *int) *PropertyUpdateOne {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *PropertyUpdateOne) AddViewCount(v int) *PropertyUpdateOne {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PropertyUpdateOne) SetPublishedAt(v time.Time) *PropertyUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillablePublishedAt(v *time.Time) *PropertyUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *PropertyUpdateOne) ClearPublishedAt() *PropertyUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PropertyUpdateOne) SetUpdatedAt(v time.Time) *PropertyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublisher sets the "publisher" edge to the User entity.
func (_u *PropertyUpdateOne) SetPublisher(v *User) *PropertyUpdateOne {
	return _u.SetPublisherID(v.ID)
}

// AddContactIDs adds the "contacts" edge to the Contact entity by IDs.
func (_u *PropertyUpdateOne) AddContactIDs(ids ...int) *PropertyUpdateOne {
	_u.mutation.AddContactIDs(ids...)
	return _u
}

// AddContacts adds the "contacts" edges to the Contact entity.
func (_u *PropertyUpdateOne) AddContacts(v ...*Contact) *PropertyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContactIDs(ids...)
}

// AddImageIDs adds the "images" edge to the PropertyImage entity by IDs.
func (_u *PropertyUpdateOne) AddImageIDs(ids ...int) *PropertyUpdateOne {
	_u.mutation.AddImageIDs(ids...)
	return _u
}

// AddImages adds the "images" edges to the PropertyImage entity.
func (_u *PropertyUpdateOne) AddImages(v ...*PropertyImage) *PropertyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddImageIDs(ids...)
}

// Mutation returns the PropertyMutation object of the builder.
func (_u *PropertyUpdateOne) Mutation() *PropertyMutation {
	return _u.mutation
}

// ClearPublisher clears the "publisher" edge to the User entity.
func (_u *PropertyUpdateOne) ClearPublisher() *PropertyUpdateOne {
	_u.mutation.ClearPublisher()
	return _u
}

// ClearContacts clears all "contacts" edges to the Contact entity.
func (_u *PropertyUpdateOne) ClearContacts() *PropertyUpdateOne {
	_u.mutation.ClearContacts()
	return _u
}

// RemoveContactIDs removes the "contacts" edge to Contact entities by IDs.
func (_u *PropertyUpdateOne) RemoveContactIDs(ids ...int) *PropertyUpdateOne {
	_u.mutation.RemoveContactIDs(ids...)
	return _u
}

// RemoveContacts removes "contacts" edges to Contact entities.
func (_u *PropertyUpdateOne) RemoveContacts(v ...*Contact) *PropertyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContactIDs(ids...)
}

// ClearImages clears all "images" edges to the PropertyImage entity.
func (_u *PropertyUpdateOne) ClearImages() *PropertyUpdateOne {
	_u.mutation.ClearImages()
	return _u
}

// RemoveImageIDs removes the "images" edge to PropertyImage entities by IDs.
func (_u *PropertyUpdateOne) RemoveImageIDs(ids ...int) *PropertyUpdateOne {
	_u.mutation.RemoveImageIDs(ids...)
	return _u
}

// RemoveImages removes "images" edges to PropertyImage entities.
func (_u *PropertyUpdateOne) RemoveImages(v ...*PropertyImage) *PropertyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveImageIDs(ids...)
}

// Where appends a list predicates to the PropertyUpdate builder.
func (_u *PropertyUpdateOne) Where(ps ...predicate.Property) *PropertyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PropertyUpdateOne) Select(field string, fields ...string) *PropertyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Property entity.
func (_u *PropertyUpdateOne) Save(ctx context.Context) (*Property, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PropertyUpdateOne) SaveX(ctx context.Context) *Property {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PropertyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PropertyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PropertyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := property.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PropertyUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := property.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`client: validator failed for field "Property.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := property.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`client: validator failed for field "Property.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PropertyType(); ok {
		if err := property.PropertyTypeValidator(v); err != nil {
			return &ValidationError{Name: "property_type", err: fmt.Errorf(`client: validator failed for field "Property.property_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Price(); ok {
		if err := property.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`client: validator failed for field "Property.price": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := property.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`client: validator failed for field "Property.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := property.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`client: validator failed for field "Property.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.District(); ok {
		if err := property.DistrictValidator(v); err != nil {
			return &ValidationError{Name: "district", err: fmt.Errorf(`client: validator failed for field "Property.district": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Municipality(); ok {
		if err := property.MunicipalityValidator(v); err != nil {
			return &ValidationError{Name: "municipality", err: fmt.Errorf(`client: validator failed for field "Property.municipality": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Parish(); ok {
		if err := property.ParishValidator(v); err != nil {
			return &ValidationError{Name: "parish", err: fmt.Errorf(`client: validator failed for field "Property.parish": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PostalCode(); ok {
		if err := property.PostalCodeValidator(v); err != nil {
			return &ValidationError{Name: "postal_code", err: fmt.Errorf(`client: validator failed for field "Property.postal_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := property.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`client: validator failed for field "Property.country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bedrooms(); ok {
		if err := property.BedroomsValidator(v); err != nil {
			return &ValidationError{Name: "bedrooms", err: fmt.Errorf(`client: validator failed for field "Property.bedrooms": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bathrooms(); ok {
		if err := property.BathroomsValidator(v); err != nil {
			return &ValidationError{Name: "bathrooms", err: fmt.Errorf(`client: validator failed for field "Property.bathrooms": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AreaSqm(); ok {
		if err := property.AreaSqmValidator(v); err != nil {
			return &ValidationError{Name: "area_sqm", err: fmt.Errorf(`client: validator failed for field "Property.area_sqm": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LandAreaSqm(); ok {
		if err := property.LandAreaSqmValidator(v); err != nil {
			return &ValidationError{Name: "land_area_sqm", err: fmt.Errorf(`client: validator failed for field "Property.land_area_sqm": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ParkingSpaces(); ok {
		if err := property.ParkingSpacesValidator(v); err != nil {
			return &ValidationError{Name: "parking_spaces", err: fmt.Errorf(`client: validator failed for field "Property.parking_spaces": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EnergyRating(); ok {
		if err := property.EnergyRatingValidator(v); err != nil {
			return &ValidationError{Name: "energy_rating", err: fmt.Errorf(`client: validator failed for field "Property.energy_rating": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VirtualTourURL(); ok {
		if err := property.VirtualTourURLValidator(v); err != nil {
			return &ValidationError{Name: "virtual_tour_url", err: fmt.Errorf(`client: validator failed for field "Property.virtual_tour_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublisherID(); ok {
		if err := property.PublisherIDValidator(v); err != nil {
			return &ValidationError{Name: "publisher_id", err: fmt.Errorf(`client: validator failed for field "Property.publisher_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ViewCount(); ok {
		if err := property.ViewCountValidator(v); err != nil {
			return &ValidationError{Name: "view_count", err: fmt.Errorf(`client: validator failed for field "Property.view_count": %w`, err)}
		}
	}
	if _u.mutation.PublisherCleared() && len(_u.mutation.PublisherIDs()) > 0 {
		return errors.New(`client: clearing a required unique edge "Property.publisher"`)
	}
	return nil
}

func (_u *PropertyUpdateOne) sqlSave(ctx context.Context) (_node *Property, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(property.Table, property.Columns, sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`client: missing "Property.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, property.FieldID)
		for _, f := range fields {
			if !property.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("client: invalid field %q for query", f)}
			}
			if f != property.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(property.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(property.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.PropertyType(); ok {
		_spec.SetField(property.FieldPropertyType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(property.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(property.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(property.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsPublished(); ok {
		_spec.SetField(property.FieldIsPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(property.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.District(); ok {
		_spec.SetField(property.FieldDistrict, field.TypeString, value)
	}
	if value, ok := _u.mutation.Municipality(); ok {
		_spec.SetField(property.FieldMunicipality, field.TypeString, value)
	}
	if value, ok := _u.mutation.Parish(); ok {
		_spec.SetField(property.FieldParish, field.TypeString, value)
	}
	if _u.mutation.ParishCleared() {
		_spec.ClearField(property.FieldParish, field.TypeString)
	}
	if value, ok := _u.mutation.PostalCode(); ok {
		_spec.SetField(property.FieldPostalCode, field.TypeString, value)
	}
	if _u.mutation.PostalCodeCleared() {
		_spec.ClearField(property.FieldPostalCode, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(property.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(property.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(property.FieldLatitude, field.TypeFloat64, value)
	}
	if _u.mutation.LatitudeCleared() {
		_spec.ClearField(property.FieldLatitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(property.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(property.FieldLongitude, field.TypeFloat64, value)
	}
	if _u.mutation.LongitudeCleared() {
		_spec.ClearField(property.FieldLongitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Bedrooms(); ok {
		_spec.SetField(property.FieldBedrooms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBedrooms(); ok {
		_spec.AddField(property.FieldBedrooms, field.TypeInt, value)
	}
	if _u.mutation.BedroomsCleared() {
		_spec.ClearField(property.FieldBedrooms, field.TypeInt)
	}
	if value, ok := _u.mutation.Bathrooms(); ok {
		_spec.SetField(property.FieldBathrooms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBathrooms(); ok {
		_spec.AddField(property.FieldBathrooms, field.TypeInt, value)
	}
	if _u.mutation.BathroomsCleared() {
		_spec.ClearField(property.FieldBathrooms, field.TypeInt)
	}
	if value, ok := _u.mutation.AreaSqm(); ok {
		_spec.SetField(property.FieldAreaSqm, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAreaSqm(); ok {
		_spec.AddField(property.FieldAreaSqm, field.TypeFloat64, value)
	}
	if _u.mutation.AreaSqmCleared() {
		_spec.ClearField(property.FieldAreaSqm, field.TypeFloat64)
	}
	if value, ok := _u.mutation.LandAreaSqm(); ok {
		_spec.SetField(property.FieldLandAreaSqm, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLandAreaSqm(); ok {
		_spec.AddField(property.FieldLandAreaSqm, field.TypeFloat64, value)
	}
	if _u.mutation.LandAreaSqmCleared() {
		_spec.ClearField(property.FieldLandAreaSqm, field.TypeFloat64)
	}
	if value, ok := _u.mutation.YearBuilt(); ok {
		_spec.SetField(property.FieldYearBuilt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYearBuilt(); ok {
		_spec.AddField(property.FieldYearBuilt, field.TypeInt, value)
	}
	if _u.mutation.YearBuiltCleared() {
		_spec.ClearField(property.FieldYearBuilt, field.TypeInt)
	}
	if value, ok := _u.mutation.Floor(); ok {
		_spec.SetField(property.FieldFloor, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFloor(); ok {
		_spec.AddField(property.FieldFloor, field.TypeInt, value)
	}
	if _u.mutation.FloorCleared() {
		_spec.ClearField(property.FieldFloor, field.TypeInt)
	}
	if value, ok := _u.mutation.TotalFloors(); ok {
		_spec.SetField(property.FieldTotalFloors, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalFloors(); ok {
		_spec.AddField(property.FieldTotalFloors, field.TypeInt, value)
	}
	if _u.mutation.TotalFloorsCleared() {
		_spec.ClearField(property.FieldTotalFloors, field.TypeInt)
	}
	if value, ok := _u.mutation.ParkingSpaces(); ok {
		_spec.SetField(property.FieldParkingSpaces, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParkingSpaces(); ok {
		_spec.AddField(property.FieldParkingSpaces, field.TypeInt, value)
	}
	if _u.mutation.ParkingSpacesCleared() {
		_spec.ClearField(property.FieldParkingSpaces, field.TypeInt)
	}
	if value, ok := _u.mutation.HasGarage(); ok {
		_spec.SetField(property.FieldHasGarage, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HasGarden(); ok {
		_spec.SetField(property.FieldHasGarden, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HasPool(); ok {
		_spec.SetField(property.FieldHasPool, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HasElevator(); ok {
		_spec.SetField(property.FieldHasElevator, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnergyRating(); ok {
		_spec.SetField(property.FieldEnergyRating, field.TypeEnum, value)
	}
	if _u.mutation.EnergyRatingCleared() {
		_spec.ClearField(property.FieldEnergyRating, field.TypeEnum)
	}
	if value, ok := _u.mutation.VirtualTourURL(); ok {
		_spec.SetField(property.FieldVirtualTourURL, field.TypeString, value)
	}
	if _u.mutation.VirtualTourURLCleared() {
		_spec.ClearField(property.FieldVirtualTourURL, field.TypeString)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(property.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(property.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(property.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(property.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(property.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PublisherCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   property.PublisherTable,
			Columns: []string{property.PublisherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PublisherIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   property.PublisherTable,
			Columns: []string{property.PublisherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContactsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   property.ContactsTable,
			Columns: property.ContactsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContactsIDs(); len(nodes) > 0 && !_u.mutation.ContactsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   property.ContactsTable,
			Columns: property.ContactsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContactsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   property.ContactsTable,
			Columns: property.ContactsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   property.ImagesTable,
			Columns: []string{property.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertyimage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedImagesIDs(); len(nodes) > 0 && !_u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   property.ImagesTable,
			Columns: []string{property.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertyimage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ImagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   property.ImagesTable,
			Columns: []string{property.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertyimage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Property{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{property.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
