// Code generated by ent, DO NOT EDIT.

package client

import (
	"context"
	"errors"
	"fmt"
	"immo-lux/internal/database/ent/client/property"
	"immo-lux/internal/database/ent/client/propertyimage"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PropertyImageCreate is the builder for creating a PropertyImage entity.
type PropertyImageCreate struct {
	config
	mutation *PropertyImageMutation
	hooks    []Hook
}

// SetPropertyID sets the "property_id" field.
func (_c *PropertyImageCreate) SetPropertyID(v int) *PropertyImageCreate {
	_c.mutation.SetPropertyID(v)
	return _c
}

// SetImageData sets the "image_data" field.
func (_c *PropertyImageCreate) SetImageData(v []byte) *PropertyImageCreate {
	_c.mutation.SetImageData(v)
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *PropertyImageCreate) SetContentType(v string) *PropertyImageCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetFileSize sets the "file_size" field.
func (_c *PropertyImageCreate) SetFileSize(v int) *PropertyImageCreate {
	_c.mutation.SetFileSize(v)
	return _c
}

// SetWidth sets the "width" field.
func (_c *PropertyImageCreate) SetWidth(v int) *PropertyImageCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetHeight sets the "height" field.
func (_c *PropertyImageCreate) SetHeight(v int) *PropertyImageCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetDisplayOrder sets the "display_order" field.
func (_c *PropertyImageCreate) SetDisplayOrder(v int) *PropertyImageCreate {
	_c.mutation.SetDisplayOrder(v)
	return _c
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_c *PropertyImageCreate) SetNillableDisplayOrder(v *int) *PropertyImageCreate {
	if v != nil {
		_c.SetDisplayOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PropertyImageCreate) SetCreatedAt(v time.Time) *PropertyImageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PropertyImageCreate) SetNillableCreatedAt(v *time.Time) *PropertyImageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetProperty sets the "property" edge to the Property entity.
func (_c *PropertyImageCreate) SetProperty(v *Property) *PropertyImageCreate {
	return _c.SetPropertyID(v.ID)
}

// Mutation returns the PropertyImageMutation object of the builder.
func (_c *PropertyImageCreate) Mutation() *PropertyImageMutation {
	return _c.mutation
}

// Save creates the PropertyImage in the database.
func (_c *PropertyImageCreate) Save(ctx context.Context) (*PropertyImage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PropertyImageCreate) SaveX(ctx context.Context) *PropertyImage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PropertyImageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PropertyImageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PropertyImageCreate) defaults() {
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		v := propertyimage.DefaultDisplayOrder
		_c.mutation.SetDisplayOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := propertyimage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PropertyImageCreate) check() error {
	if _, ok := _c.mutation.PropertyID(); !ok {
		return &ValidationError{Name: "property_id", err: errors.New(`client: missing required field "PropertyImage.property_id"`)}
	}
	if v, ok := _c.mutation.PropertyID(); ok {
		if err := propertyimage.PropertyIDValidator(v); err != nil {
			return &ValidationError{Name: "property_id", err: fmt.Errorf(`client: validator failed for field "PropertyImage.property_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ImageData(); !ok {
		return &ValidationError{Name: "image_data", err: errors.New(`client: missing required field "PropertyImage.image_data"`)}
	}
	if v, ok := _c.mutation.ImageData(); ok {
		if err := propertyimage.ImageDataValidator(v); err != nil {
			return &ValidationError{Name: "image_data", err: fmt.Errorf(`client: validator failed for field "PropertyImage.image_data": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`client: missing required field "PropertyImage.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := propertyimage.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`client: validator failed for field "PropertyImage.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		return &ValidationError{Name: "file_size", err: errors.New(`client: missing required field "PropertyImage.file_size"`)}
	}
	if v, ok := _c.mutation.FileSize(); ok {
		if err := propertyimage.FileSizeValidator(v); err != nil {
			return &ValidationError{Name: "file_size", err: fmt.Errorf(`client: validator failed for field "PropertyImage.file_size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Width(); !ok {
		return &ValidationError{Name: "width", err: errors.New(`client: missing required field "PropertyImage.width"`)}
	}
	if v, ok := _c.mutation.Width(); ok {
		if err := propertyimage.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`client: validator failed for field "PropertyImage.width": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`client: missing required field "PropertyImage.height"`)}
	}
	if v, ok := _c.mutation.Height(); ok {
		if err := propertyimage.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`client: validator failed for field "PropertyImage.height": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		return &ValidationError{Name: "display_order", err: errors.New(`client: missing required field "PropertyImage.display_order"`)}
	}
	if v, ok := _c.mutation.DisplayOrder(); ok {
		if err := propertyimage.DisplayOrderValidator(v); err != nil {
			return &ValidationError{Name: "display_order", err: fmt.Errorf(`client: validator failed for field "PropertyImage.display_order": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`client: missing required field "PropertyImage.created_at"`)}
	}
	if len(_c.mutation.PropertyIDs()) == 0 {
		return &ValidationError{Name: "property", err: errors.New(`client: missing required edge "PropertyImage.property"`)}
	}
	return nil
}

func (_c *PropertyImageCreate) sqlSave(ctx context.Context) (*PropertyImage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PropertyImageCreate) createSpec() (*PropertyImage, *sqlgraph.CreateSpec) {
	var (
		_node = &PropertyImage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(propertyimage.Table, sqlgraph.NewFieldSpec(propertyimage.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ImageData(); ok {
		_spec.SetField(propertyimage.FieldImageData, field.TypeBytes, value)
		_node.ImageData = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(propertyimage.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.FileSize(); ok {
		_spec.SetField(propertyimage.FieldFileSize, field.TypeInt, value)
		_node.FileSize = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(propertyimage.FieldWidth, field.TypeInt, value)
		_node.Width = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(propertyimage.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.DisplayOrder(); ok {
		_spec.SetField(propertyimage.FieldDisplayOrder, field.TypeInt, value)
		_node.DisplayOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(propertyimage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PropertyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   propertyimage.PropertyTable,
			Columns: []string{propertyimage.PropertyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PropertyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PropertyImageCreateBulk is the builder for creating many PropertyImage entities in bulk.
type PropertyImageCreateBulk struct {
	config
	err      error
	builders []*PropertyImageCreate
}

// Save creates the PropertyImage entities in the database.
func (_c *PropertyImageCreateBulk) Save(ctx context.Context) ([]*PropertyImage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PropertyImage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PropertyImageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PropertyImageCreateBulk) SaveX(ctx context.Context) []*PropertyImage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PropertyImageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PropertyImageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
