// Code generated by ent, DO NOT EDIT.

package client

import (
	"fmt"
	"immo-lux/internal/database/ent/client/property"
	"immo-lux/internal/database/ent/client/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Property is the model entity for the Property schema.
type Property struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// PropertyType holds the value of the "property_type" field.
	PropertyType property.PropertyType `json:"property_type,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// Status holds the value of the "status" field.
	Status property.Status `json:"status,omitempty"`
	// IsPublished holds the value of the "is_published" field.
	IsPublished bool `json:"is_published,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// District holds the value of the "district" field.
	District string `json:"district,omitempty"`
	// Municipality holds the value of the "municipality" field.
	Municipality string `json:"municipality,omitempty"`
	// Parish holds the value of the "parish" field.
	Parish *string `json:"parish,omitempty"`
	// PostalCode holds the value of the "postal_code" field.
	PostalCode *string `json:"postal_code,omitempty"`
	// Country holds the value of the "country" field.
	Country string `json:"country,omitempty"`
	// Latitude holds the value of the "latitude" field.
	Latitude *float64 `json:"latitude,omitempty"`
	// Longitude holds the value of the "longitude" field.
	Longitude *float64 `json:"longitude,omitempty"`
	// Bedrooms holds the value of the "bedrooms" field.
	Bedrooms *int `json:"bedrooms,omitempty"`
	// Bathrooms holds the value of the "bathrooms" field.
	Bathrooms *int `json:"bathrooms,omitempty"`
	// AreaSqm holds the value of the "area_sqm" field.
	AreaSqm *float64 `json:"area_sqm,omitempty"`
	// LandAreaSqm holds the value of the "land_area_sqm" field.
	LandAreaSqm *float64 `json:"land_area_sqm,omitempty"`
	// YearBuilt holds the value of the "year_built" field.
	YearBuilt *int `json:"year_built,omitempty"`
	// Floor holds the value of the "floor" field.
	Floor *int `json:"floor,omitempty"`
	// TotalFloors holds the value of the "total_floors" field.
	TotalFloors *int `json:"total_floors,omitempty"`
	// ParkingSpaces holds the value of the "parking_spaces" field.
	ParkingSpaces *int `json:"parking_spaces,omitempty"`
	// HasGarage holds the value of the "has_garage" field.
	HasGarage bool `json:"has_garage,omitempty"`
	// HasGarden holds the value of the "has_garden" field.
	HasGarden bool `json:"has_garden,omitempty"`
	// HasPool holds the value of the "has_pool" field.
	HasPool bool `json:"has_pool,omitempty"`
	// HasElevator holds the value of the "has_elevator" field.
	HasElevator bool `json:"has_elevator,omitempty"`
	// EnergyRating holds the value of the "energy_rating" field.
	EnergyRating *property.EnergyRating `json:"energy_rating,omitempty"`
	// VirtualTourURL holds the value of the "virtual_tour_url" field.
	VirtualTourURL *string `json:"virtual_tour_url,omitempty"`
	// PublisherID holds the value of the "publisher_id" field.
	PublisherID int `json:"publisher_id,omitempty"`
	// ViewCount holds the value of the "view_count" field.
	ViewCount int `json:"view_count,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PropertyQuery when eager-loading is set.
	Edges        PropertyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PropertyEdges holds the relations/edges for other nodes in the graph.
type PropertyEdges struct {
	// Publisher holds the value of the publisher edge.
	Publisher *User `json:"publisher,omitempty"`
	// Contacts holds the value of the contacts edge.
	Contacts []*Contact `json:"contacts,omitempty"`
	// Images holds the value of the images edge.
	Images []*PropertyImage `json:"images,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// PublisherOrErr returns the Publisher value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PropertyEdges) PublisherOrErr() (*User, error) {
	if e.Publisher != nil {
		return e.Publisher, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "publisher"}
}

// ContactsOrErr returns the Contacts value or an error if the edge
// was not loaded in eager-loading.
func (e PropertyEdges) ContactsOrErr() ([]*Contact, error) {
	if e.loadedTypes[1] {
		return e.Contacts, nil
	}
	return nil, &NotLoadedError{edge: "contacts"}
}

// ImagesOrErr returns the Images value or an error if the edge
// was not loaded in eager-loading.
func (e PropertyEdges) ImagesOrErr() ([]*PropertyImage, error) {
	if e.loadedTypes[2] {
		return e.Images, nil
	}
	return nil, &NotLoadedError{edge: "images"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Property) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case property.FieldIsPublished, property.FieldHasGarage, property.FieldHasGarden, property.FieldHasPool, property.FieldHasElevator:
			values[i] = new(sql.NullBool)
		case property.FieldPrice, property.FieldLatitude, property.FieldLongitude, property.FieldAreaSqm, property.FieldLandAreaSqm:
			values[i] = new(sql.NullFloat64)
		case property.FieldID, property.FieldBedrooms, property.FieldBathrooms, property.FieldYearBuilt, property.FieldFloor, property.FieldTotalFloors, property.FieldParkingSpaces, property.FieldPublisherID, property.FieldViewCount:
			values[i] = new(sql.NullInt64)
		case property.FieldTitle, property.FieldDescription, property.FieldPropertyType, property.FieldStatus, property.FieldAddress, property.FieldDistrict, property.FieldMunicipality, property.FieldParish, property.FieldPostalCode, property.FieldCountry, property.FieldEnergyRating, property.FieldVirtualTourURL:
			values[i] = new(sql.NullString)
		case property.FieldPublishedAt, property.FieldCreatedAt, property.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Property fields.
func (_m *Property) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case property.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case property.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case property.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case property.FieldPropertyType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field property_type", values[i])
			} else if value.Valid {
				_m.PropertyType = property.PropertyType(value.String)
			}
		case property.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.Float64
			}
		case property.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = property.Status(value.String)
			}
		case property.FieldIsPublished:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_published", values[i])
			} else if value.Valid {
				_m.IsPublished = value.Bool
			}
		case property.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case property.FieldDistrict:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field district", values[i])
			} else if value.Valid {
				_m.District = value.String
			}
		case property.FieldMunicipality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field municipality", values[i])
			} else if value.Valid {
				_m.Municipality = value.String
			}
		case property.FieldParish:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parish", values[i])
			} else if value.Valid {
				_m.Parish = new(string)
				*_m.Parish = value.String
			}
		case property.FieldPostalCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field postal_code", values[i])
			} else if value.Valid {
				_m.PostalCode = new(string)
				*_m.PostalCode = value.String
			}
		case property.FieldCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country", values[i])
			} else if value.Valid {
				_m.Country = value.String
			}
		case property.FieldLatitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field latitude", values[i])
			} else if value.Valid {
				_m.Latitude = new(float64)
				*_m.Latitude = value.Float64
			}
		case property.FieldLongitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field longitude", values[i])
			} else if value.Valid {
				_m.Longitude = new(float64)
				*_m.Longitude = value.Float64
			}
		case property.FieldBedrooms:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bedrooms", values[i])
			} else if value.Valid {
				_m.Bedrooms = new(int)
				*_m.Bedrooms = int(value.Int64)
			}
		case property.FieldBathrooms:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bathrooms", values[i])
			} else if value.Valid {
				_m.Bathrooms = new(int)
				*_m.Bathrooms = int(value.Int64)
			}
		case property.FieldAreaSqm:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field area_sqm", values[i])
			} else if value.Valid {
				_m.AreaSqm = new(float64)
				*_m.AreaSqm = value.Float64
			}
		case property.FieldLandAreaSqm:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field land_area_sqm", values[i])
			} else if value.Valid {
				_m.LandAreaSqm = new(float64)
				*_m.LandAreaSqm = value.Float64
			}
		case property.FieldYearBuilt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field year_built", values[i])
			} else if value.Valid {
				_m.YearBuilt = new(int)
				*_m.YearBuilt = int(value.Int64)
			}
		case property.FieldFloor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field floor", values[i])
			} else if value.Valid {
				_m.Floor = new(int)
				*_m.Floor = int(value.Int64)
			}
		case property.FieldTotalFloors:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_floors", values[i])
			} else if value.Valid {
				_m.TotalFloors = new(int)
				*_m.TotalFloors = int(value.Int64)
			}
		case property.FieldParkingSpaces:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parking_spaces", values[i])
			} else if value.Valid {
				_m.ParkingSpaces = new(int)
				*_m.ParkingSpaces = int(value.Int64)
			}
		case property.FieldHasGarage:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field has_garage", values[i])
			} else if value.Valid {
				_m.HasGarage = value.Bool
			}
		case property.FieldHasGarden:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field has_garden", values[i])
			} else if value.Valid {
				_m.HasGarden = value.Bool
			}
		case property.FieldHasPool:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field has_pool", values[i])
			} else if value.Valid {
				_m.HasPool = value.Bool
			}
		case property.FieldHasElevator:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field has_elevator", values[i])
			} else if value.Valid {
				_m.HasElevator = value.Bool
			}
		case property.FieldEnergyRating:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field energy_rating", values[i])
			} else if value.Valid {
				_m.EnergyRating = new(property.EnergyRating)
				*_m.EnergyRating = property.EnergyRating(value.String)
			}
		case property.FieldVirtualTourURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field virtual_tour_url", values[i])
			} else if value.Valid {
				_m.VirtualTourURL = new(string)
				*_m.VirtualTourURL = value.String
			}
		case property.FieldPublisherID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field publisher_id", values[i])
			} else if value.Valid {
				_m.PublisherID = int(value.Int64)
			}
		case property.FieldViewCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field view_count", values[i])
			} else if value.Valid {
				_m.ViewCount = int(value.Int64)
			}
		case property.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		case property.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case property.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Property.
// This includes values selected through modifiers, order, etc.
func (_m *Property) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPublisher queries the "publisher" edge of the Property entity.
func (_m *Property) QueryPublisher() *UserQuery {
	return NewPropertyClient(_m.config).QueryPublisher(_m)
}

// QueryContacts queries the "contacts" edge of the Property entity.
func (_m *Property) QueryContacts() *ContactQuery {
	return NewPropertyClient(_m.config).QueryContacts(_m)
}

// QueryImages queries the "images" edge of the Property entity.
func (_m *Property) QueryImages() *PropertyImageQuery {
	return NewPropertyClient(_m.config).QueryImages(_m)
}

// Update returns a builder for updating this Property.
// Note that you need to call Property.Unwrap() before calling this method if this Property
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Property) Update() *PropertyUpdateOne {
	return NewPropertyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Property entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Property) Unwrap() *Property {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("client: Property is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Property) String() string {
	var builder strings.Builder
	builder.WriteString("Property(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("property_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.PropertyType))
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("is_published=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPublished))
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("district=")
	builder.WriteString(_m.District)
	builder.WriteString(", ")
	builder.WriteString("municipality=")
	builder.WriteString(_m.Municipality)
	builder.WriteString(", ")
	if v := _m.Parish; v != nil {
		builder.WriteString("parish=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PostalCode; v != nil {
		builder.WriteString("postal_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("country=")
	builder.WriteString(_m.Country)
	builder.WriteString(", ")
	if v := _m.Latitude; v != nil {
		builder.WriteString("latitude=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Longitude; v != nil {
		builder.WriteString("longitude=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Bedrooms; v != nil {
		builder.WriteString("bedrooms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Bathrooms; v != nil {
		builder.WriteString("bathrooms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AreaSqm; v != nil {
		builder.WriteString("area_sqm=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LandAreaSqm; v != nil {
		builder.WriteString("land_area_sqm=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.YearBuilt; v != nil {
		builder.WriteString("year_built=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Floor; v != nil {
		builder.WriteString("floor=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TotalFloors; v != nil {
		builder.WriteString("total_floors=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ParkingSpaces; v != nil {
		builder.WriteString("parking_spaces=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("has_garage=")
	builder.WriteString(fmt.Sprintf("%v", _m.HasGarage))
	builder.WriteString(", ")
	builder.WriteString("has_garden=")
	builder.WriteString(fmt.Sprintf("%v", _m.HasGarden))
	builder.WriteString(", ")
	builder.WriteString("has_pool=")
	builder.WriteString(fmt.Sprintf("%v", _m.HasPool))
	builder.WriteString(", ")
	builder.WriteString("has_elevator=")
	builder.WriteString(fmt.Sprintf("%v", _m.HasElevator))
	builder.WriteString(", ")
	if v := _m.EnergyRating; v != nil {
		builder.WriteString("energy_rating=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.VirtualTourURL; v != nil {
		builder.WriteString("virtual_tour_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("publisher_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublisherID))
	builder.WriteString(", ")
	builder.WriteString("view_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ViewCount))
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Properties is a parsable slice of Property.
type Properties []*Property
