// Code generated by ent, DO NOT EDIT.

package client

import (
	"context"
	"errors"
	"fmt"
	"immo-lux/internal/database/ent/client/contact"
	"immo-lux/internal/database/ent/client/property"
	"immo-lux/internal/database/ent/client/propertyimage"
	"immo-lux/internal/database/ent/client/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PropertyCreate is the builder for creating a Property entity.
type PropertyCreate struct {
	config
	mutation *PropertyMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *PropertyCreate) SetTitle(v string) *PropertyCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PropertyCreate) SetDescription(v string) *PropertyCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetPropertyType sets the "property_type" field.
func (_c *PropertyCreate) SetPropertyType(v property.PropertyType) *PropertyCreate {
	_c.mutation.SetPropertyType(v)
	return _c
}

// SetNillablePropertyType sets the "property_type" field if the given value is not nil.
func (_c *PropertyCreate) SetNillablePropertyType(v *property.PropertyType) *PropertyCreate {
	if v != nil {
		_c.SetPropertyType(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *PropertyCreate) SetPrice(v float64) *PropertyCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PropertyCreate) SetStatus(v property.Status) *PropertyCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableStatus(v *property.Status) *PropertyCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetIsPublished sets the "is_published" field.
func (_c *PropertyCreate) SetIsPublished(v bool) *PropertyCreate {
	_c.mutation.SetIsPublished(v)
	return _c
}

// SetNillableIsPublished sets the "is_published" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableIsPublished(v *bool) *PropertyCreate {
	if v != nil {
		_c.SetIsPublished(*v)
	}
	return _c
}

// SetAddress sets the "address" field.
func (_c *PropertyCreate) SetAddress(v string) *PropertyCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetDistrict sets the "district" field.
func (_c *PropertyCreate) SetDistrict(v string) *PropertyCreate {
	_c.mutation.SetDistrict(v)
	return _c
}

// SetMunicipality sets the "municipality" field.
func (_c *PropertyCreate) SetMunicipality(v string) *PropertyCreate {
	_c.mutation.SetMunicipality(v)
	return _c
}

// SetParish sets the "parish" field.
func (_c *PropertyCreate) SetParish(v string) *PropertyCreate {
	_c.mutation.SetParish(v)
	return _c
}

// SetNillableParish sets the "parish" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableParish(v *string) *PropertyCreate {
	if v != nil {
		_c.SetParish(*v)
	}
	return _c
}

// SetPostalCode sets the "postal_code" field.
func (_c *PropertyCreate) SetPostalCode(v string) *PropertyCreate {
	_c.mutation.SetPostalCode(v)
	return _c
}

// SetNillablePostalCode sets the "postal_code" field if the given value is not nil.
func (_c *PropertyCreate) SetNillablePostalCode(v *string) *PropertyCreate {
	if v != nil {
		_c.SetPostalCode(*v)
	}
	return _c
}

// SetCountry sets the "country" field.
func (_c *PropertyCreate) SetCountry(v string) *PropertyCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableCountry(v *string) *PropertyCreate {
	if v != nil {
		_c.SetCountry(*v)
	}
	return _c
}

// SetLatitude sets the "latitude" field.
func (_c *PropertyCreate) SetLatitude(v float64) *PropertyCreate {
	_c.mutation.SetLatitude(v)
	return _c
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableLatitude(v *float64) *PropertyCreate {
	if v != nil {
		_c.SetLatitude(*v)
	}
	return _c
}

// SetLongitude sets the "longitude" field.
func (_c *PropertyCreate) SetLongitude(v float64) *PropertyCreate {
	_c.mutation.SetLongitude(v)
	return _c
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableLongitude(v *float64) *PropertyCreate {
	if v != nil {
		_c.SetLongitude(*v)
	}
	return _c
}

// SetBedrooms sets the "bedrooms" field.
func (_c *PropertyCreate) SetBedrooms(v int) *PropertyCreate {
	_c.mutation.SetBedrooms(v)
	return _c
}

// SetNillableBedrooms sets the "bedrooms" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableBedrooms(v *int) *PropertyCreate {
	if v != nil {
		_c.SetBedrooms(*v)
	}
	return _c
}

// SetBathrooms sets the "bathrooms" field.
func (_c *PropertyCreate) SetBathrooms(v int) *PropertyCreate {
	_c.mutation.SetBathrooms(v)
	return _c
}

// SetNillableBathrooms sets the "bathrooms" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableBathrooms(v *int) *PropertyCreate {
	if v != nil {
		_c.SetBathrooms(*v)
	}
	return _c
}

// SetAreaSqm sets the "area_sqm" field.
func (_c *PropertyCreate) SetAreaSqm(v float64) *PropertyCreate {
	_c.mutation.SetAreaSqm(v)
	return _c
}

// SetNillableAreaSqm sets the "area_sqm" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableAreaSqm(v *float64) *PropertyCreate {
	if v != nil {
		_c.SetAreaSqm(*v)
	}
	return _c
}

// SetLandAreaSqm sets the "land_area_sqm" field.
func (_c *PropertyCreate) SetLandAreaSqm(v float64) *PropertyCreate {
	_c.mutation.SetLandAreaSqm(v)
	return _c
}

// SetNillableLandAreaSqm sets the "land_area_sqm" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableLandAreaSqm(v *float64) *PropertyCreate {
	if v != nil {
		_c.SetLandAreaSqm(*v)
	}
	return _c
}

// SetYearBuilt sets the "year_built" field.
func (_c *PropertyCreate) SetYearBuilt(v int) *PropertyCreate {
	_c.mutation.SetYearBuilt(v)
	return _c
}

// SetNillableYearBuilt sets the "year_built" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableYearBuilt(v *int) *PropertyCreate {
	if v != nil {
		_c.SetYearBuilt(*v)
	}
	return _c
}

// SetFloor sets the "floor" field.
func (_c *PropertyCreate) SetFloor(v int) *PropertyCreate {
	_c.mutation.SetFloor(v)
	return _c
}

// SetNillableFloor sets the "floor" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableFloor(v *int) *PropertyCreate {
	if v != nil {
		_c.SetFloor(*v)
	}
	return _c
}

// SetTotalFloors sets the "total_floors" field.
func (_c *PropertyCreate) SetTotalFloors(v int) *PropertyCreate {
	_c.mutation.SetTotalFloors(v)
	return _c
}

// SetNillableTotalFloors sets the "total_floors" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableTotalFloors(v *int) *PropertyCreate {
	if v != nil {
		_c.SetTotalFloors(*v)
	}
	return _c
}

// SetParkingSpaces sets the "parking_spaces" field.
func (_c *PropertyCreate) SetParkingSpaces(v int) *PropertyCreate {
	_c.mutation.SetParkingSpaces(v)
	return _c
}

// SetNillableParkingSpaces sets the "parking_spaces" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableParkingSpaces(v *int) *PropertyCreate {
	if v != nil {
		_c.SetParkingSpaces(*v)
	}
	return _c
}

// SetHasGarage sets the "has_garage" field.
func (_c *PropertyCreate) SetHasGarage(v bool) *PropertyCreate {
	_c.mutation.SetHasGarage(v)
	return _c
}

// SetNillableHasGarage sets the "has_garage" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableHasGarage(v *bool) *PropertyCreate {
	if v != nil {
		_c.SetHasGarage(*v)
	}
	return _c
}

// SetHasGarden sets the "has_garden" field.
func (_c *PropertyCreate) SetHasGarden(v bool) *PropertyCreate {
	_c.mutation.SetHasGarden(v)
	return _c
}

// SetNillableHasGarden sets the "has_garden" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableHasGarden(v *bool) *PropertyCreate {
	if v != nil {
		_c.SetHasGarden(*v)
	}
	return _c
}

// SetHasPool sets the "has_pool" field.
func (_c *PropertyCreate) SetHasPool(v bool) *PropertyCreate {
	_c.mutation.SetHasPool(v)
	return _c
}

// SetNillableHasPool sets the "has_pool" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableHasPool(v *bool) *PropertyCreate {
	if v != nil {
		_c.SetHasPool(*v)
	}
	return _c
}

// SetHasElevator sets the "has_elevator" field.
func (_c *PropertyCreate) SetHasElevator(v bool) *PropertyCreate {
	_c.mutation.SetHasElevator(v)
	return _c
}

// SetNillableHasElevator sets the "has_elevator" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableHasElevator(v *bool) *PropertyCreate {
	if v != nil {
		_c.SetHasElevator(*v)
	}
	return _c
}

// SetEnergyRating sets the "energy_rating" field.
func (_c *PropertyCreate) SetEnergyRating(v property.EnergyRating) *PropertyCreate {
	_c.mutation.SetEnergyRating(v)
	return _c
}

// SetNillableEnergyRating sets the "energy_rating" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableEnergyRating(v *property.EnergyRating) *PropertyCreate {
	if v != nil {
		_c.SetEnergyRating(*v)
	}
	return _c
}

// SetVirtualTourURL sets the "virtual_tour_url" field.
func (_c *PropertyCreate) SetVirtualTourURL(v string) *PropertyCreate {
	_c.mutation.SetVirtualTourURL(v)
	return _c
}

// SetNillableVirtualTourURL sets the "virtual_tour_url" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableVirtualTourURL(v *string) *PropertyCreate {
	if v != nil {
		_c.SetVirtualTourURL(*v)
	}
	return _c
}

// SetPublisherID sets the "publisher_id" field.
func (_c *PropertyCreate) SetPublisherID(v int) *PropertyCreate {
	_c.mutation.SetPublisherID(v)
	return _c
}

// SetViewCount sets the "view_count" field.
func (_c *PropertyCreate) SetViewCount(v int) *PropertyCreate {
	_c.mutation.SetViewCount(v)
	return _c
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableViewCount(v *int) *PropertyCreate {
	if v != nil {
		_c.SetViewCount(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *PropertyCreate) SetPublishedAt(v time.Time) *PropertyCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *PropertyCreate) SetNillablePublishedAt(v *time.Time) *PropertyCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PropertyCreate) SetCreatedAt(v time.Time) *PropertyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableCreatedAt(v *time.Time) *PropertyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PropertyCreate) SetUpdatedAt(v time.Time) *PropertyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PropertyCreate) SetNillableUpdatedAt(v *time.Time) *PropertyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPublisher sets the "publisher" edge to the User entity.
func (_c *PropertyCreate) SetPublisher(v *User) *PropertyCreate {
	return _c.SetPublisherID(v.ID)
}

// AddContactIDs adds the "contacts" edge to the Contact entity by IDs.
func (_c *PropertyCreate) AddContactIDs(ids ...int) *PropertyCreate {
	_c.mutation.AddContactIDs(ids...)
	return _c
}

// AddContacts adds the "contacts" edges to the Contact entity.
func (_c *PropertyCreate) AddContacts(v ...*Contact) *PropertyCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddContactIDs(ids...)
}

// AddImageIDs adds the "images" edge to the PropertyImage entity by IDs.
func (_c *PropertyCreate) AddImageIDs(ids ...int) *PropertyCreate {
	_c.mutation.AddImageIDs(ids...)
	return _c
}

// AddImages adds the "images" edges to the PropertyImage entity.
func (_c *PropertyCreate) AddImages(v ...*PropertyImage) *PropertyCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddImageIDs(ids...)
}

// Mutation returns the PropertyMutation object of the builder.
func (_c *PropertyCreate) Mutation() *PropertyMutation {
	return _c.mutation
}

// Save creates the Property in the database.
func (_c *PropertyCreate) Save(ctx context.Context) (*Property, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PropertyCreate) SaveX(ctx context.Context) *Property {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PropertyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PropertyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PropertyCreate) defaults() {
	if _, ok := _c.mutation.PropertyType(); !ok {
		v := property.DefaultPropertyType
		_c.mutation.SetPropertyType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := property.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.IsPublished(); !ok {
		v := property.DefaultIsPublished
		_c.mutation.SetIsPublished(v)
	}
	if _, ok := _c.mutation.Country(); !ok {
		v := property.DefaultCountry
		_c.mutation.SetCountry(v)
	}
	if _, ok := _c.mutation.HasGarage(); !ok {
		v := property.DefaultHasGarage
		_c.mutation.SetHasGarage(v)
	}
	if _, ok := _c.mutation.HasGarden(); !ok {
		v := property.DefaultHasGarden
		_c.mutation.SetHasGarden(v)
	}
	if _, ok := _c.mutation.HasPool(); !ok {
		v := property.DefaultHasPool
		_c.mutation.SetHasPool(v)
	}
	if _, ok := _c.mutation.HasElevator(); !ok {
		v := property.DefaultHasElevator
		_c.mutation.SetHasElevator(v)
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		v := property.DefaultViewCount
		_c.mutation.SetViewCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := property.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := property.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PropertyCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`client: missing required field "Property.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := property.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`client: validator failed for field "Property.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`client: missing required field "Property.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := property.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`client: validator failed for field "Property.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PropertyType(); !ok {
		return &ValidationError{Name: "property_type", err: errors.New(`client: missing required field "Property.property_type"`)}
	}
	if v, ok := _c.mutation.PropertyType(); ok {
		if err := property.PropertyTypeValidator(v); err != nil {
			return &ValidationError{Name: "property_type", err: fmt.Errorf(`client: validator failed for field "Property.property_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`client: missing required field "Property.price"`)}
	}
	if v, ok := _c.mutation.Price(); ok {
		if err := property.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`client: validator failed for field "Property.price": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`client: missing required field "Property.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := property.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`client: validator failed for field "Property.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsPublished(); !ok {
		return &ValidationError{Name: "is_published", err: errors.New(`client: missing required field "Property.is_published"`)}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`client: missing required field "Property.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := property.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`client: validator failed for field "Property.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.District(); !ok {
		return &ValidationError{Name: "district", err: errors.New(`client: missing required field "Property.district"`)}
	}
	if v, ok := _c.mutation.District(); ok {
		if err := property.DistrictValidator(v); err != nil {
			return &ValidationError{Name: "district", err: fmt.Errorf(`client: validator failed for field "Property.district": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Municipality(); !ok {
		return &ValidationError{Name: "municipality", err: errors.New(`client: missing required field "Property.municipality"`)}
	}
	if v, ok := _c.mutation.Municipality(); ok {
		if err := property.MunicipalityValidator(v); err != nil {
			return &ValidationError{Name: "municipality", err: fmt.Errorf(`client: validator failed for field "Property.municipality": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Parish(); ok {
		if err := property.ParishValidator(v); err != nil {
			return &ValidationError{Name: "parish", err: fmt.Errorf(`client: validator failed for field "Property.parish": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PostalCode(); ok {
		if err := property.PostalCodeValidator(v); err != nil {
			return &ValidationError{Name: "postal_code", err: fmt.Errorf(`client: validator failed for field "Property.postal_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Country(); !ok {
		return &ValidationError{Name: "country", err: errors.New(`client: missing required field "Property.country"`)}
	}
	if v, ok := _c.mutation.Country(); ok {
		if err := property.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`client: validator failed for field "Property.country": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Bedrooms(); ok {
		if err := property.BedroomsValidator(v); err != nil {
			return &ValidationError{Name: "bedrooms", err: fmt.Errorf(`client: validator failed for field "Property.bedrooms": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Bathrooms(); ok {
		if err := property.BathroomsValidator(v); err != nil {
			return &ValidationError{Name: "bathrooms", err: fmt.Errorf(`client: validator failed for field "Property.bathrooms": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AreaSqm(); ok {
		if err := property.AreaSqmValidator(v); err != nil {
			return &ValidationError{Name: "area_sqm", err: fmt.Errorf(`client: validator failed for field "Property.area_sqm": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LandAreaSqm(); ok {
		if err := property.LandAreaSqmValidator(v); err != nil {
			return &ValidationError{Name: "land_area_sqm", err: fmt.Errorf(`client: validator failed for field "Property.land_area_sqm": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ParkingSpaces(); ok {
		if err := property.ParkingSpacesValidator(v); err != nil {
			return &ValidationError{Name: "parking_spaces", err: fmt.Errorf(`client: validator failed for field "Property.parking_spaces": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HasGarage(); !ok {
		return &ValidationError{Name: "has_garage", err: errors.New(`client: missing required field "Property.has_garage"`)}
	}
	if _, ok := _c.mutation.HasGarden(); !ok {
		return &ValidationError{Name: "has_garden", err: errors.New(`client: missing required field "Property.has_garden"`)}
	}
	if _, ok := _c.mutation.HasPool(); !ok {
		return &ValidationError{Name: "has_pool", err: errors.New(`client: missing required field "Property.has_pool"`)}
	}
	if _, ok := _c.mutation.HasElevator(); !ok {
		return &ValidationError{Name: "has_elevator", err: errors.New(`client: missing required field "Property.has_elevator"`)}
	}
	if v, ok := _c.mutation.EnergyRating(); ok {
		if err := property.EnergyRatingValidator(v); err != nil {
			return &ValidationError{Name: "energy_rating", err: fmt.Errorf(`client: validator failed for field "Property.energy_rating": %w`, err)}
		}
	}
	if v, ok := _c.mutation.VirtualTourURL(); ok {
		if err := property.VirtualTourURLValidator(v); err != nil {
			return &ValidationError{Name: "virtual_tour_url", err: fmt.Errorf(`client: validator failed for field "Property.virtual_tour_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PublisherID(); !ok {
		return &ValidationError{Name: "publisher_id", err: errors.New(`client: missing required field "Property.publisher_id"`)}
	}
	if v, ok := _c.mutation.PublisherID(); ok {
		if err := property.PublisherIDValidator(v); err != nil {
			return &ValidationError{Name: "publisher_id", err: fmt.Errorf(`client: validator failed for field "Property.publisher_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		return &ValidationError{Name: "view_count", err: errors.New(`client: missing required field "Property.view_count"`)}
	}
	if v, ok := _c.mutation.ViewCount(); ok {
		if err := property.ViewCountValidator(v); err != nil {
			return &ValidationError{Name: "view_count", err: fmt.Errorf(`client: validator failed for field "Property.view_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`client: missing required field "Property.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`client: missing required field "Property.updated_at"`)}
	}
	if len(_c.mutation.PublisherIDs()) == 0 {
		return &ValidationError{Name: "publisher", err: errors.New(`client: missing required edge "Property.publisher"`)}
	}
	return nil
}

func (_c *PropertyCreate) sqlSave(ctx context.Context) (*Property, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PropertyCreate) createSpec() (*Property, *sqlgraph.CreateSpec) {
	var (
		_node = &Property{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(property.Table, sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(property.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(property.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.PropertyType(); ok {
		_spec.SetField(property.FieldPropertyType, field.TypeEnum, value)
		_node.PropertyType = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(property.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(property.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.IsPublished(); ok {
		_spec.SetField(property.FieldIsPublished, field.TypeBool, value)
		_node.IsPublished = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(property.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.District(); ok {
		_spec.SetField(property.FieldDistrict, field.TypeString, value)
		_node.District = value
	}
	if value, ok := _c.mutation.Municipality(); ok {
		_spec.SetField(property.FieldMunicipality, field.TypeString, value)
		_node.Municipality = value
	}
	if value, ok := _c.mutation.Parish(); ok {
		_spec.SetField(property.FieldParish, field.TypeString, value)
		_node.Parish = &value
	}
	if value, ok := _c.mutation.PostalCode(); ok {
		_spec.SetField(property.FieldPostalCode, field.TypeString, value)
		_node.PostalCode = &value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(property.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := _c.mutation.Latitude(); ok {
		_spec.SetField(property.FieldLatitude, field.TypeFloat64, value)
		_node.Latitude = &value
	}
	if value, ok := _c.mutation.Longitude(); ok {
		_spec.SetField(property.FieldLongitude, field.TypeFloat64, value)
		_node.Longitude = &value
	}
	if value, ok := _c.mutation.Bedrooms(); ok {
		_spec.SetField(property.FieldBedrooms, field.TypeInt, value)
		_node.Bedrooms = &value
	}
	if value, ok := _c.mutation.Bathrooms(); ok {
		_spec.SetField(property.FieldBathrooms, field.TypeInt, value)
		_node.Bathrooms = &value
	}
	if value, ok := _c.mutation.AreaSqm(); ok {
		_spec.SetField(property.FieldAreaSqm, field.TypeFloat64, value)
		_node.AreaSqm = &value
	}
	if value, ok := _c.mutation.LandAreaSqm(); ok {
		_spec.SetField(property.FieldLandAreaSqm, field.TypeFloat64, value)
		_node.LandAreaSqm = &value
	}
	if value, ok := _c.mutation.YearBuilt(); ok {
		_spec.SetField(property.FieldYearBuilt, field.TypeInt, value)
		_node.YearBuilt = &value
	}
	if value, ok := _c.mutation.Floor(); ok {
		_spec.SetField(property.FieldFloor, field.TypeInt, value)
		_node.Floor = &value
	}
	if value, ok := _c.mutation.TotalFloors(); ok {
		_spec.SetField(property.FieldTotalFloors, field.TypeInt, value)
		_node.TotalFloors = &value
	}
	if value, ok := _c.mutation.ParkingSpaces(); ok {
		_spec.SetField(property.FieldParkingSpaces, field.TypeInt, value)
		_node.ParkingSpaces = &value
	}
	if value, ok := _c.mutation.HasGarage(); ok {
		_spec.SetField(property.FieldHasGarage, field.TypeBool, value)
		_node.HasGarage = value
	}
	if value, ok := _c.mutation.HasGarden(); ok {
		_spec.SetField(property.FieldHasGarden, field.TypeBool, value)
		_node.HasGarden = value
	}
	if value, ok := _c.mutation.HasPool(); ok {
		_spec.SetField(property.FieldHasPool, field.TypeBool, value)
		_node.HasPool = value
	}
	if value, ok := _c.mutation.HasElevator(); ok {
		_spec.SetField(property.FieldHasElevator, field.TypeBool, value)
		_node.HasElevator = value
	}
	if value, ok := _c.mutation.EnergyRating(); ok {
		_spec.SetField(property.FieldEnergyRating, field.TypeEnum, value)
		_node.EnergyRating = &value
	}
	if value, ok := _c.mutation.VirtualTourURL(); ok {
		_spec.SetField(property.FieldVirtualTourURL, field.TypeString, value)
		_node.VirtualTourURL = &value
	}
	if value, ok := _c.mutation.ViewCount(); ok {
		_spec.SetField(property.FieldViewCount, field.TypeInt, value)
		_node.ViewCount = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(property.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(property.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(property.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.PublisherIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   property.PublisherTable,
			Columns: []string{property.PublisherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PublisherID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ContactsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   property.ContactsTable,
			Columns: property.ContactsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ImagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   property.ImagesTable,
			Columns: []string{property.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertyimage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PropertyCreateBulk is the builder for creating many Property entities in bulk.
type PropertyCreateBulk struct {
	config
	err      error
	builders []*PropertyCreate
}

// Save creates the Property entities in the database.
func (_c *PropertyCreateBulk) Save(ctx context.Context) ([]*Property, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Property, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PropertyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PropertyCreateBulk) SaveX(ctx context.Context) []*Property {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PropertyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PropertyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
