// Code generated by ent, DO NOT EDIT.

package client

import (
	"fmt"
	"immo-lux/internal/database/ent/client/property"
	"immo-lux/internal/database/ent/client/propertyimage"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PropertyImage is the model entity for the PropertyImage schema.
type PropertyImage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PropertyID holds the value of the "property_id" field.
	PropertyID int `json:"property_id,omitempty"`
	// ImageData holds the value of the "image_data" field.
	ImageData []byte `json:"-"`
	// ContentType holds the value of the "content_type" field.
	ContentType string `json:"content_type,omitempty"`
	// FileSize holds the value of the "file_size" field.
	FileSize int `json:"file_size,omitempty"`
	// Width holds the value of the "width" field.
	Width int `json:"width,omitempty"`
	// Height holds the value of the "height" field.
	Height int `json:"height,omitempty"`
	// DisplayOrder holds the value of the "display_order" field.
	DisplayOrder int `json:"display_order,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PropertyImageQuery when eager-loading is set.
	Edges        PropertyImageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PropertyImageEdges holds the relations/edges for other nodes in the graph.
type PropertyImageEdges struct {
	// Property holds the value of the property edge.
	Property *Property `json:"property,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PropertyOrErr returns the Property value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PropertyImageEdges) PropertyOrErr() (*Property, error) {
	if e.Property != nil {
		return e.Property, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: property.Label}
	}
	return nil, &NotLoadedError{edge: "property"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PropertyImage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case propertyimage.FieldImageData:
			values[i] = new([]byte)
		case propertyimage.FieldID, propertyimage.FieldPropertyID, propertyimage.FieldFileSize, propertyimage.FieldWidth, propertyimage.FieldHeight, propertyimage.FieldDisplayOrder:
			values[i] = new(sql.NullInt64)
		case propertyimage.FieldContentType:
			values[i] = new(sql.NullString)
		case propertyimage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PropertyImage fields.
func (_m *PropertyImage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case propertyimage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case propertyimage.FieldPropertyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field property_id", values[i])
			} else if value.Valid {
				_m.PropertyID = int(value.Int64)
			}
		case propertyimage.FieldImageData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field image_data", values[i])
			} else if value != nil {
				_m.ImageData = *value
			}
		case propertyimage.FieldContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_type", values[i])
			} else if value.Valid {
				_m.ContentType = value.String
			}
		case propertyimage.FieldFileSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_size", values[i])
			} else if value.Valid {
				_m.FileSize = int(value.Int64)
			}
		case propertyimage.FieldWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value.Valid {
				_m.Width = int(value.Int64)
			}
		case propertyimage.FieldHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				_m.Height = int(value.Int64)
			}
		case propertyimage.FieldDisplayOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field display_order", values[i])
			} else if value.Valid {
				_m.DisplayOrder = int(value.Int64)
			}
		case propertyimage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PropertyImage.
// This includes values selected through modifiers, order, etc.
func (_m *PropertyImage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProperty queries the "property" edge of the PropertyImage entity.
func (_m *PropertyImage) QueryProperty() *PropertyQuery {
	return NewPropertyImageClient(_m.config).QueryProperty(_m)
}

// Update returns a builder for updating this PropertyImage.
// Note that you need to call PropertyImage.Unwrap() before calling this method if this PropertyImage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PropertyImage) Update() *PropertyImageUpdateOne {
	return NewPropertyImageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PropertyImage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PropertyImage) Unwrap() *PropertyImage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("client: PropertyImage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PropertyImage) String() string {
	var builder strings.Builder
	builder.WriteString("PropertyImage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("property_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PropertyID))
	builder.WriteString(", ")
	builder.WriteString("image_data=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("content_type=")
	builder.WriteString(_m.ContentType)
	builder.WriteString(", ")
	builder.WriteString("file_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileSize))
	builder.WriteString(", ")
	builder.WriteString("width=")
	builder.WriteString(fmt.Sprintf("%v", _m.Width))
	builder.WriteString(", ")
	builder.WriteString("height=")
	builder.WriteString(fmt.Sprintf("%v", _m.Height))
	builder.WriteString(", ")
	builder.WriteString("display_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.DisplayOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PropertyImages is a parsable slice of PropertyImage.
type PropertyImages []*PropertyImage
