// Code generated by ent, DO NOT EDIT.

package client

import (
	"context"
	"errors"
	"fmt"
	"immo-lux/internal/database/ent/client/predicate"
	"immo-lux/internal/database/ent/client/ratelimit"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RateLimitUpdate is the builder for updating RateLimit entities.
type RateLimitUpdate struct {
	config
	hooks    []Hook
	mutation *RateLimitMutation
}

// Where appends a list predicates to the RateLimitUpdate builder.
func (_u *RateLimitUpdate) Where(ps ...predicate.RateLimit) *RateLimitUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *RateLimitUpdate) SetEmail(v string) *RateLimitUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *RateLimitUpdate) SetNillableEmail(v *string) *RateLimitUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *RateLimitUpdate) SetIPAddress(v string) *RateLimitUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *RateLimitUpdate) SetNillableIPAddress(v *string) *RateLimitUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *RateLimitUpdate) SetAction(v string) *RateLimitUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *RateLimitUpdate) SetNillableAction(v *string) *RateLimitUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *RateLimitUpdate) SetAttemptCount(v int) *RateLimitUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *RateLimitUpdate) SetNillableAttemptCount(v *int) *RateLimitUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *RateLimitUpdate) AddAttemptCount(v int) *RateLimitUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetWindowStart sets the "window_start" field.
func (_u *RateLimitUpdate) SetWindowStart(v time.Time) *RateLimitUpdate {
	_u.mutation.SetWindowStart(v)
	return _u
}

// SetNillableWindowStart sets the "window_start" field if the given value is not nil.
func (_u *RateLimitUpdate) SetNillableWindowStart(v *time.Time) *RateLimitUpdate {
	if v != nil {
		_u.SetWindowStart(*v)
	}
	return _u
}

// SetBlockedUntil sets the "blocked_until" field.
func (_u *RateLimitUpdate) SetBlockedUntil(v time.Time) *RateLimitUpdate {
	_u.mutation.SetBlockedUntil(v)
	return _u
}

// SetNillableBlockedUntil sets the "blocked_until" field if the given value is not nil.
func (_u *RateLimitUpdate) SetNillableBlockedUntil(v *time.Time) *RateLimitUpdate {
	if v != nil {
		_u.SetBlockedUntil(*v)
	}
	return _u
}

// ClearBlockedUntil clears the value of the "blocked_until" field.
func (_u *RateLimitUpdate) ClearBlockedUntil() *RateLimitUpdate {
	_u.mutation.ClearBlockedUntil()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RateLimitUpdate) SetUpdatedAt(v time.Time) *RateLimitUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RateLimitMutation object of the builder.
func (_u *RateLimitUpdate) Mutation() *RateLimitMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RateLimitUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RateLimitUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RateLimitUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RateLimitUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RateLimitUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ratelimit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RateLimitUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := ratelimit.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`client: validator failed for field "RateLimit.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := ratelimit.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`client: validator failed for field "RateLimit.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := ratelimit.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`client: validator failed for field "RateLimit.action": %w`, err)}
		}
	}
	return nil
}

func (_u *RateLimitUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ratelimit.Table, ratelimit.Columns, sqlgraph.NewFieldSpec(ratelimit.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(ratelimit.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(ratelimit.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(ratelimit.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(ratelimit.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(ratelimit.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WindowStart(); ok {
		_spec.SetField(ratelimit.FieldWindowStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BlockedUntil(); ok {
		_spec.SetField(ratelimit.FieldBlockedUntil, field.TypeTime, value)
	}
	if _u.mutation.BlockedUntilCleared() {
		_spec.ClearField(ratelimit.FieldBlockedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ratelimit.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ratelimit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RateLimitUpdateOne is the builder for updating a single RateLimit entity.
type RateLimitUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RateLimitMutation
}

// SetEmail sets the "email" field.
func (_u *RateLimitUpdateOne) SetEmail(v string) *RateLimitUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *RateLimitUpdateOne) SetNillableEmail(v *string) *RateLimitUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *RateLimitUpdateOne) SetIPAddress(v string) *RateLimitUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *RateLimitUpdateOne) SetNillableIPAddress(v *string) *RateLimitUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *RateLimitUpdateOne) SetAction(v string) *RateLimitUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *RateLimitUpdateOne) SetNillableAction(v *string) *RateLimitUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *RateLimitUpdateOne) SetAttemptCount(v int) *RateLimitUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *RateLimitUpdateOne) SetNillableAttemptCount(v *int) *RateLimitUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *RateLimitUpdateOne) AddAttemptCount(v int) *RateLimitUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetWindowStart sets the "window_start" field.
func (_u *RateLimitUpdateOne) SetWindowStart(v time.Time) *RateLimitUpdateOne {
	_u.mutation.SetWindowStart(v)
	return _u
}

// SetNillableWindowStart sets the "window_start" field if the given value is not nil.
func (_u *RateLimitUpdateOne) SetNillableWindowStart(v *time.Time) *RateLimitUpdateOne {
	if v != nil {
		_u.SetWindowStart(*v)
	}
	return _u
}

// SetBlockedUntil sets the "blocked_until" field.
func (_u *RateLimitUpdateOne) SetBlockedUntil(v time.Time) *RateLimitUpdateOne {
	_u.mutation.SetBlockedUntil(v)
	return _u
}

// SetNillableBlockedUntil sets the "blocked_until" field if the given value is not nil.
func (_u *RateLimitUpdateOne) SetNillableBlockedUntil(v *time.Time) *RateLimitUpdateOne {
	if v != nil {
		_u.SetBlockedUntil(*v)
	}
	return _u
}

// ClearBlockedUntil clears the value of the "blocked_until" field.
func (_u *RateLimitUpdateOne) ClearBlockedUntil() *RateLimitUpdateOne {
	_u.mutation.ClearBlockedUntil()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RateLimitUpdateOne) SetUpdatedAt(v time.Time) *RateLimitUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RateLimitMutation object of the builder.
func (_u *RateLimitUpdateOne) Mutation() *RateLimitMutation {
	return _u.mutation
}

// Where appends a list predicates to the RateLimitUpdate builder.
func (_u *RateLimitUpdateOne) Where(ps ...predicate.RateLimit) *RateLimitUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RateLimitUpdateOne) Select(field string, fields ...string) *RateLimitUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RateLimit entity.
func (_u *RateLimitUpdateOne) Save(ctx context.Context) (*RateLimit, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RateLimitUpdateOne) SaveX(ctx context.Context) *RateLimit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RateLimitUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RateLimitUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RateLimitUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ratelimit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RateLimitUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := ratelimit.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`client: validator failed for field "RateLimit.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := ratelimit.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`client: validator failed for field "RateLimit.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := ratelimit.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`client: validator failed for field "RateLimit.action": %w`, err)}
		}
	}
	return nil
}

func (_u *RateLimitUpdateOne) sqlSave(ctx context.Context) (_node *RateLimit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ratelimit.Table, ratelimit.Columns, sqlgraph.NewFieldSpec(ratelimit.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`client: missing "RateLimit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ratelimit.FieldID)
		for _, f := range fields {
			if !ratelimit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("client: invalid field %q for query", f)}
			}
			if f != ratelimit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(ratelimit.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(ratelimit.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(ratelimit.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(ratelimit.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(ratelimit.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WindowStart(); ok {
		_spec.SetField(ratelimit.FieldWindowStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BlockedUntil(); ok {
		_spec.SetField(ratelimit.FieldBlockedUntil, field.TypeTime, value)
	}
	if _u.mutation.BlockedUntilCleared() {
		_spec.ClearField(ratelimit.FieldBlockedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ratelimit.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &RateLimit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ratelimit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
