// Code generated by ent, DO NOT EDIT.

package client

import (
	"fmt"
	"immo-lux/internal/database/ent/client/ratelimit"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// RateLimit is the model entity for the RateLimit schema.
type RateLimit struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// IPAddress holds the value of the "ip_address" field.
	IPAddress string `json:"ip_address,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// AttemptCount holds the value of the "attempt_count" field.
	AttemptCount int `json:"attempt_count,omitempty"`
	// WindowStart holds the value of the "window_start" field.
	WindowStart time.Time `json:"window_start,omitempty"`
	// BlockedUntil holds the value of the "blocked_until" field.
	BlockedUntil *time.Time `json:"blocked_until,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RateLimit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ratelimit.FieldID, ratelimit.FieldAttemptCount:
			values[i] = new(sql.NullInt64)
		case ratelimit.FieldEmail, ratelimit.FieldIPAddress, ratelimit.FieldAction:
			values[i] = new(sql.NullString)
		case ratelimit.FieldWindowStart, ratelimit.FieldBlockedUntil, ratelimit.FieldCreatedAt, ratelimit.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RateLimit fields.
func (_m *RateLimit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ratelimit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ratelimit.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case ratelimit.FieldIPAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_address", values[i])
			} else if value.Valid {
				_m.IPAddress = value.String
			}
		case ratelimit.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case ratelimit.FieldAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_count", values[i])
			} else if value.Valid {
				_m.AttemptCount = int(value.Int64)
			}
		case ratelimit.FieldWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field window_start", values[i])
			} else if value.Valid {
				_m.WindowStart = value.Time
			}
		case ratelimit.FieldBlockedUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field blocked_until", values[i])
			} else if value.Valid {
				_m.BlockedUntil = new(time.Time)
				*_m.BlockedUntil = value.Time
			}
		case ratelimit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ratelimit.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RateLimit.
// This includes values selected through modifiers, order, etc.
func (_m *RateLimit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RateLimit.
// Note that you need to call RateLimit.Unwrap() before calling this method if this RateLimit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RateLimit) Update() *RateLimitUpdateOne {
	return NewRateLimitClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RateLimit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RateLimit) Unwrap() *RateLimit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("client: RateLimit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RateLimit) String() string {
	var builder strings.Builder
	builder.WriteString("RateLimit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("ip_address=")
	builder.WriteString(_m.IPAddress)
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("attempt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptCount))
	builder.WriteString(", ")
	builder.WriteString("window_start=")
	builder.WriteString(_m.WindowStart.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.BlockedUntil; v != nil {
		builder.WriteString("blocked_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RateLimits is a parsable slice of RateLimit.
type RateLimits []*RateLimit
