// Code generated by ent, DO NOT EDIT.

package client

import (
	"immo-lux/internal/database/ent/client/session"
	"immo-lux/internal/database/ent/client/user"
	"immo-lux/internal/database/ent/client/userauth"
	"immo-lux/internal/database/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescUserID is the schema descriptor for user_id field.
	sessionDescUserID := sessionFields[0].Descriptor()
	// session.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	session.UserIDValidator = sessionDescUserID.Validators[0].(func(int) error)
	// sessionDescSessionToken is the schema descriptor for session_token field.
	sessionDescSessionToken := sessionFields[1].Descriptor()
	// session.SessionTokenValidator is a validator for the "session_token" field. It is called by the builders before save.
	session.SessionTokenValidator = func() func(string) error {
		validators := sessionDescSessionToken.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(session_token string) error {
			for _, fn := range fns {
				if err := fn(session_token); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sessionDescIsActive is the schema descriptor for is_active field.
	sessionDescIsActive := sessionFields[2].Descriptor()
	// session.DefaultIsActive holds the default value on creation for the is_active field.
	session.DefaultIsActive = sessionDescIsActive.Default.(bool)
	// sessionDescRememberMe is the schema descriptor for remember_me field.
	sessionDescRememberMe := sessionFields[3].Descriptor()
	// session.DefaultRememberMe holds the default value on creation for the remember_me field.
	session.DefaultRememberMe = sessionDescRememberMe.Default.(bool)
	// sessionDescInvalidatedReason is the schema descriptor for invalidated_reason field.
	sessionDescInvalidatedReason := sessionFields[6].Descriptor()
	// session.InvalidatedReasonValidator is a validator for the "invalidated_reason" field. It is called by the builders before save.
	session.InvalidatedReasonValidator = sessionDescInvalidatedReason.Validators[0].(func(string) error)
	// sessionDescIPAddress is the schema descriptor for ip_address field.
	sessionDescIPAddress := sessionFields[7].Descriptor()
	// session.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	session.IPAddressValidator = sessionDescIPAddress.Validators[0].(func(string) error)
	// sessionDescUserAgent is the schema descriptor for user_agent field.
	sessionDescUserAgent := sessionFields[8].Descriptor()
	// session.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	session.UserAgentValidator = sessionDescUserAgent.Validators[0].(func(string) error)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[9].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionFields[10].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(func() time.Time)
	// session.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	session.UpdateDefaultUpdatedAt = sessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescFirstName is the schema descriptor for first_name field.
	userDescFirstName := userFields[0].Descriptor()
	// user.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	user.FirstNameValidator = func() func(string) error {
		validators := userDescFirstName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(first_name string) error {
			for _, fn := range fns {
				if err := fn(first_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescLastName is the schema descriptor for last_name field.
	userDescLastName := userFields[1].Descriptor()
	// user.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	user.LastNameValidator = func() func(string) error {
		validators := userDescLastName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(last_name string) error {
			for _, fn := range fns {
				if err := fn(last_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[3].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	userauthFields := schema.UserAuth{}.Fields()
	_ = userauthFields
	// userauthDescUserID is the schema descriptor for user_id field.
	userauthDescUserID := userauthFields[0].Descriptor()
	// userauth.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	userauth.UserIDValidator = userauthDescUserID.Validators[0].(func(int) error)
	// userauthDescHash is the schema descriptor for hash field.
	userauthDescHash := userauthFields[1].Descriptor()
	// userauth.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	userauth.HashValidator = userauthDescHash.Validators[0].(func(string) error)
	// userauthDescIsLocked is the schema descriptor for is_locked field.
	userauthDescIsLocked := userauthFields[2].Descriptor()
	// userauth.DefaultIsLocked holds the default value on creation for the is_locked field.
	userauth.DefaultIsLocked = userauthDescIsLocked.Default.(bool)
	// userauthDescLockedReason is the schema descriptor for locked_reason field.
	userauthDescLockedReason := userauthFields[3].Descriptor()
	// userauth.LockedReasonValidator is a validator for the "locked_reason" field. It is called by the builders before save.
	userauth.LockedReasonValidator = userauthDescLockedReason.Validators[0].(func(string) error)
	// userauthDescFailedLoginAttempts is the schema descriptor for failed_login_attempts field.
	userauthDescFailedLoginAttempts := userauthFields[4].Descriptor()
	// userauth.DefaultFailedLoginAttempts holds the default value on creation for the failed_login_attempts field.
	userauth.DefaultFailedLoginAttempts = userauthDescFailedLoginAttempts.Default.(int)
	// userauth.FailedLoginAttemptsValidator is a validator for the "failed_login_attempts" field. It is called by the builders before save.
	userauth.FailedLoginAttemptsValidator = userauthDescFailedLoginAttempts.Validators[0].(func(int) error)
	// userauthDescCreatedAt is the schema descriptor for created_at field.
	userauthDescCreatedAt := userauthFields[7].Descriptor()
	// userauth.DefaultCreatedAt holds the default value on creation for the created_at field.
	userauth.DefaultCreatedAt = userauthDescCreatedAt.Default.(func() time.Time)
	// userauthDescUpdatedAt is the schema descriptor for updated_at field.
	userauthDescUpdatedAt := userauthFields[8].Descriptor()
	// userauth.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userauth.DefaultUpdatedAt = userauthDescUpdatedAt.Default.(func() time.Time)
	// userauth.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userauth.UpdateDefaultUpdatedAt = userauthDescUpdatedAt.UpdateDefault.(func() time.Time)
}
